### ISSUE TITLE
Letters of Support (Girlfriends)

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#104]
We've chosen to include this attachment for Senior/PI section -- Current or Pending allowed

**Comment by tarabyun** [comment]
Both the Girlfriends and I will be soliciting letters of support from collaborators. They're in a folder in our shared Dropbox. Still in development.

**Comment by starakaj** [comment]
Cool, I'll take Tara's suggestion of adding "boilerplate compliments" before sending these to our recommenders
