### ISSUE TITLE
Biographical Sketch (Sam)

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#105]
We've chosen to include this attachment for Senior/PI section

**Comment by tarabyun** [comment]
Will be including this. Exists in our shared Dropbox folder (but not yet finalized).

**Comment by starakaj** [comment]
Sorry, just to be clear, do I need to take action on this ticket right now? Last I remember I was waiting on feedback for this.

**Comment by tarabyun** [comment]
Sorry about that--I'll try to give feedback today.

**Comment by starakaj** [comment]
No problem at all, just wanted to be make sure I wasn't blocking anyone!

**Comment by gsuthers** [comment]
No rush! Just as long as we all know it's done. We need to figure out priorities on these so you're not overwhelmed with all the deliverables.
