### ISSUE TITLE
Research Strategy

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#113]
Required for "Research Plan" section.

Additional Submissions:
+ Specific Aims

+ Protection of Human Subjects

+ Data Safety Monitoring Plan (?)

+ Inclusion of Women and Minorities

+ Inclusion of Children

**Comment by tarabyun** [comment]
Specific Aims--Yes, this is required. This is a subsection of our ShareLatex doc.

Progress Report Publication List--No, I think this is for resubmissions.

Protection of Human Subjects--Yes. This is a subsection of our ShareLatex doc.

Data Safety Monitoring Plan--I think so, checking up on this now

Inclusion of Women and Minorities--Yes. This is a subsection of our ShareLatex doc.

Inclusion of Children--Yes. This is a subsection of our ShareLatex doc.

**Comment by gsuthers** [comment]
Cool. I'm updating the main comment based on your confirmations.
