### ISSUE TITLE
Upload fails after completing Syllable Practice, Word Practice and Syllable Probe

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#116]
It seems that when completing the Syllable Probe, Syllable practice and Word Practice data fails to upload. The prompts are all given correctly otherwise and all other situations work.

Word Probe - Complete - Works
Word Probe - Partial Stop - Works
Syllable Probe - Complete - Fails to Upload
Syllable Probe - Partial Stop - Works
Syllable Practice - Complete - Fails to Upload
Syllable Practice - Partial Stop - Works
Word Practice - Complete - Fails to Upload
Word Practice - Partial Stop - - Works

**Comment by starakaj** [comment]
Seems like this old ticket isn't too much use to us anymore...
