### ISSUE TITLE
Attempting to start before creating a profile removes profile creation ability

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#120]
This is a big one!

If you try to do Syllable/ Word Practice or a Test Probe before creating a Profile, you'll get a 'can't do this' message that tells you to make a Profile. BUT THEN if you go to profiles you will _sometimes_ run into a bug where every attempt to create a profile is met with that same 'you can't play syllable practice' message. 

Recreating:
This doesn't always happen on the first attempt, but it does happen consistently. So you may need to hit Start Practice/Probe a few times (I recommend switching between tabs) and then it'll happen. 

I am guess this is a memory issue because it seems to be stuck on your last input - so it may be a consequence of rapidly switching between tabs.

**Comment by starakaj** [comment]
Oh. Wild.

**Comment by starakaj** [comment]
Ok, fwiw it's possible to get out of this state by switching to and from the profiles tab again. Seems like even though the old view has left, it still wants to receive all of the touch events. Coincidentally, the "Create New Profile" button and the "Begin xxx Practice" button are on top of each other, so it looks like pressing "Create New Profile" is causing the other warning alert to appear.

**Comment by gsuthers** [comment]
Ohh that makes so much more sense! Awesome investigation skills. Let me
know how it goes!

**Comment by starakaj** [comment]
Alright, worth a test in version 1.0.1
