### ISSUE TITLE
Trainer/SLP can modify word list/ choose words to elicit

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#133]
There will be many times you would want to use your own word set, or restrict the words the client attempted.

**Comment by gsuthers** [comment]
https://workflowy.com/s/-JQ.1615P9HATA

**Comment by tarabyun** [comment]
New Feature: Selecting target categories of words for treatment
Make this an option to be set in an individual's profile
Text: "Select the categories you want to include in staRt treatment."
Display check boxes allowing user to select any of the following categories (multiple is fine; default behavior is all categories checked; selections should persist from one session to another when logged in with same profile): 
Syllabic r, as in "bird"
[this category is coded as vocalic_all]
Syllable-initial r with front vowels, as in "read"
[this category is coded as consonantal_front]
Syllable-initial r with back vowels, as in "road"
[this category is coded as consonantal_back]
Syllable-final r with front vowels, as in "deer"
[this category is coded as vocalic_front]
Syllable-final r with back vowels, as in "door"
[this category is coded as vocalic_back]
How to map category selections on to syllables/words:
See vlookup_all_stimuli_start_pilot.csv
Every item in each task is coded as one of the above-listed categories (column Category). 
When one of the tasks "Syllable Practice" and "Word Practice" is selected, present all and only the items from the selected categories. 
Total number of presentations should be the same no matter how many are selected. Therefore, go through all selected items in random order without replacement until the selected sublist is exhausted, then iterate until target number of items is reached.
I would prefer if the default behavior of the app is to apply this filtering ONLY to the "Syllable Practice" and "Word Practice" tasks, not to the Syllable Probe and Word Probe tasks. However, if it's easier to implement across-the-board filtering to start out, we can discuss.

**Comment by tarabyun** [comment]
Link to relevant CSV file: https://starfishes.slack.com/files/tara.byun/F6MCB0KC3/vlookup_all_stimuli_start_pilot.xlsx

**Comment by starakaj** [comment]
Is there design for this? Or should I just figure it out (I can totally do that btw)?

**Comment by tarabyun** [comment]
I think @gsuthers has some preliminary stuff but nothing has been finalized as yet...Geoff, maybe share what you have so Sam can put in placeholders accordingly?

**Comment by gsuthers** [comment]
Ya! Mockups have been shared via Slack but we'll finalize the design on Friday

**Comment by gsuthers** [comment]
Temp icons for /r/ categories 
[:r: Icons.zip](https://github.com/ByunLab/staRt-ionic/files/1273096/r.Icons.zip)

**Comment by gsuthers** [comment]
For now, let's add the option to select /r/ categories between selecting "Word" or "Syllable" Quest (see https://github.com/ByunLab/staRt-ionic/issues/157 for new format) and beginning the trials.

We don't need to select the session length yet, though this is a desired functionality for later. We *will* eventually want the /r/ category selection to be done in profiles and saved for each independently.

[quest2_mock](https://user-images.githubusercontent.com/11972125/30006108-c4ea4e74-90be-11e7-9fde-857ea85dc590.png)

**Comment by tarabyun** [comment]
Yes to all. Thanks!

**Comment by starakaj** [comment]
Cool, this looks great.

**Comment by gsuthers** [comment]
It would be great to have metadata on what categories were chosen but this doesn't need to be included right away. Made an issue for the future: https://github.com/ByunLab/staRt-ionic/issues/162
