### ISSUE TITLE
[BUG] Uploading fails after performing several.

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#138]
User (Amanda) reported that she is having difficulties with uploading sessions.

This is additional information on issue #116 (which I am removing from the board).

Based on Testing:
User can upload from a practice/ test session directly after completing, and the recordings are logged.

Selecting recordings allows you to upload again. A popup saying Upload Complete comes up. But it still says "Uploading..." in the bottom right and the Upload button is 'inactive'.

You can upload these as many times as you wish. 

After leaving Profiles for another tab and then returning, uploading previous recordings fails. After the Upload Error, Upload button is marked 'inactive' and the 'Uploading...' message sticks. This is true even when switching between multiple recordings. Button and message reset when leaving the Profiles tab and returning, but attempting to Upload again repeats errors.

Waiting on Profile tab after a failed upload triggers a series of new error messages automatically. This was repeatable. These repeated upload error messages pop up while on other tabs as well, suggesting that it continues to attempt uploads that have failed.

Performing Practice/Tests and attempting to upload sessions after Upload errors on Profile page automatically pushes an Upload Error. 

Closing the app and re-opening does not resolve the issue.
Neither does discarding a newly recorded session or deleting some/all sessions. Turning off the device and returning to the app does not solve the issue either.

**Comment by starakaj** [comment]
Ongoing, as I just saw this bug again. I'll have to see Cassie about this one.

**Comment by gsuthers** [comment]
Tara is still reporting to be having issues with this:
FRIDAY SEP 15
uploading is not working for me :disappointed: "server upload failed. please check your internet connection and try again," but I am connected

MONDAY SEP 18
ooks like the server is down? I tried to access byunlab.com/experigen and got this message; seems to be the same thing with byunlab.com/start?
![pasted image at 2017_09_18 03_08 pm](https://user-images.githubusercontent.com/11972125/30600520-ab21238e-9d2d-11e7-861f-14fa975a0647.png)

**Comment by catarak** [comment]
server is up now. it's running using a service that restarts the process if it crashes, so this shouldn't happen unless the entire EC2 instance is restarted.

**Comment by starakaj** [comment]
We haven't seen any issues here yet, and Cassie says she's implemented an auto-restart that should fix the issue. So I'm going to call this one fixed unless/until it comes up again.
