### ISSUE TITLE
Add a toggle for 'delete after upload' in profiles under recordings

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#142]

**Comment by starakaj** [comment]
I wonder if we shouldn't just delete these outright? Why would anyone want to keep them around?

**Comment by gsuthers** [comment]
Woops this card didn't get updated! Yes Sam, as we discussed they should be deleted outright :) Thanks for the great suggestion!

**Comment by starakaj** [comment]
So did we decide just to delete these?

**Comment by starakaj** [comment]
From @gsuthers, via Slack:

So the way it is now the app can confirm that the server downloaded successfully. If we were to implement an auto-delete protocol we might say “once the download is successful, delete!” ? How likely do you think it is that recordings will be lost?

If there is uncertainty about whether or not the upload to a server was successful then I don’t want us to have an auto-delete protocol. If we can guarantee it doesn’t delete until confirming the upload success then yes, we could automatically delete after upload.

All that said, are there use cases where a LPC might want their client to listen to a recording again. IE: remember last time? or remember this really good “staR” you gave me/ session you had?

Or might a client/child want to listen to their recordings?

**Comment by starakaj** [comment]
The recordings aren't so big that there's a lot of urgency about deleting them. Now that recordings have their metadata listed, and we have ability to delete multiple recordings at once, personally I don't think auto-delete is really necessary.

Auto-delete could be nice once we can make improvements to the server. The client could safely auto-delete the recording, but only if it knew for sure there was some way to recover it. So, we'd want to extend the server API a bit. The updated server should be able to (1) verify that a recording exists (2) allow the user to download an old recording. With those two provisions in place, I'd say auto-delete is a great idea.

In the mean time, and for the fall pilot, I'd disable it entirely.

**Comment by starakaj** [comment]
Since we've agreed not to do the autodelete, I'm considering this closed
