### ISSUE TITLE
Resources section update

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#145]
Design Needed

Resources Needed

**Comment by starakaj** [comment]
Are these links/images available? Or am I waiting on these?

**Comment by gsuthers** [comment]
Reference document. Still needs sorting for what will be in/ format.

[Master schedule for staRt app piloting_updated7AUG2017.docx](https://github.com/ByunLab/staRt-ionic/files/1272650/Master.schedule.for.staRt.app.piloting_updated7AUG2017.docx)

**Comment by gsuthers** [comment]
Okay! Here's a temporary design that solves the issue without too much work...
The LPC Filter **should lead to the current LPC Resources page** but the header should be "LPC Filter". Honestly the spot I've placed this button in is terrible. If _at all possible_ it'd be nice to move the LPC Filter to the Profiles... it should affect profiles anyway.

![tempresourcesux](https://user-images.githubusercontent.com/11972125/30342393-ca9fb3bc-97c7-11e7-9f41-093289471b50.png)

**Links for PDFs to be added are as follows**
Checklist For Interested Clinicians:
https://18798-presscdn-pagely.netdna-ssl.com/byunlab/wp-content/uploads/sites/2008/2017/03/staRt_app_clinician_checklist_expiresMAR2018.pdf

staRt User Manual:
https://18798-presscdn-pagely.netdna-ssl.com/byunlab/wp-content/uploads/sites/2008/2015/05/staRt-User-Manual_version_1.0.0.pdf

Principal Letter:
https://18798-presscdn-pagely.netdna-ssl.com/byunlab/wp-content/uploads/sites/2008/2017/03/staRt_app_principal_letter_expiresMAR2018.pdf

Parent Letter:
https://18798-presscdn-pagely.netdna-ssl.com/byunlab/wp-content/uploads/sites/2008/2017/03/staRt_app_parent_letter_expiresMAR2018.pdf

Clinician Questionnaire 1: Speech and Language History
https://18798-presscdn-pagely.netdna-ssl.com/byunlab/wp-content/uploads/sites/2008/2017/03/staRt_app_clinician_questionnaire_1_expiresMAR2018.pdf

Clinician Questionnaire 2: Speech and Language Evaluation
https://18798-presscdn-pagely.netdna-ssl.com/byunlab/wp-content/uploads/sites/2008/2017/03/staRt_app_clinician_questionnaire_2_expiresMAR2018.pdf

Pilot Tester Survey:
https://docs.google.com/forms/d/e/1FAIpQLSewiD8Uxle5WRPh5ArgUwYNQA6lktpjA8-xwSQVqinTW1IQiA/viewform?c=0&w=1

Bug Report:
https://docs.google.com/forms/d/e/1FAIpQLScfSrv-fbkMg7AaZerT0ssXAbLJ20LD2h-XZQXBFAXbyUkWmw/viewform?c=0&w=1

**Comment by starakaj** [comment]
Cool beans. Thanks for this @gsuthers, I'll get started.

**Comment by gsuthers** [comment]
naw, man! Thank you for being flexible :D

**Comment by gsuthers** [comment]
@tarabyun you may want to check that all of these links are desired/ correct

**Comment by tarabyun** [comment]
The links are correct, but I'm going to need to update some of them as soon as I receive approved amendments from our IRB, and I'm worried about links going dead/becoming obsolete. Maybe we could create some permalinks where we could stash the documents in question? Other ideas?

**Comment by starakaj** [comment]
Definitely a good idea...

**Comment by gsuthers** [comment]
Tara is suspecting we need to create some kind of Secure Box Upload and we can swap out links in an update.

**Comment by tarabyun** [comment]
hey @starakaj, I was wondering if I could get your help generating the permalinks in question. what's the best way to generate a document link that lets you swap out the underlying content without changing the URL?

**Comment by starakaj** [comment]
Hmm. One easy way way to do this would be with amazon s3, I think. You have an AWS account, right?

**Comment by tarabyun** [comment]
yep, can give you login instructions if that would be helpful
