### ISSUE TITLE
Reterm feedback buttons

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#147]
We'd like to change the terms to the following:

Great!
OK
Try Again

**Comment by starakaj** [comment]
Do we have new term for this?

**Comment by gsuthers** [comment]
We have a few options. We could go with the initial suggestion by Helen's team. At least this one suggests a 'try again', though we would need to allow the option or force it if rated low.
<img width="96" alt="screen shot 2017-09-03 at 4 05 30 pm" src="https://user-images.githubusercontent.com/11972125/30006229-cede56e8-90c1-11e7-9a5b-89fa8ff8977f.png">

Alternatively we might move in the Sand dollar direction, especially if we decide to rack them up as you play:
![quest3_mock](https://user-images.githubusercontent.com/11972125/30006228-cb80fdac-90c1-11e7-9882-dd8d7488e39d.png)

This seems like it needs to be discussed. @tarabyun do you wan the language to be changed temporarily or even to add the sand dollars in now with no effect, or would you like us to keep it as is until a design is finalized?

**Comment by tarabyun** [comment]
@gsuthers, thanks for laying this out so clearly. let's go with the originally suggested wording ('try again') for the time being, and once we implement progress tracking we can change to the sand dollar design.

**Comment by gsuthers** [comment]
@tarabyun excellent. I'll change the description to reflect this.

**Comment by gsuthers** [comment]
OH @tarabyun - if we change the text to 'try again' we should probably make that mean something. 
For now we could see if @starakaj can make it so pressing 'Try Again' does not progress the user to the next trial. How do you two feel about that? Sam, how much work/ how risky would it be to implement?

**Comment by tarabyun** [comment]
Actually, I disagree--I think "try again" can mean "try again on the next word," not necessarily "try this word again." I'm OK with "try again" as a replacement for "poor" with no change in the functionality of the button.

**Comment by gsuthers** [comment]
Oh cool, I didn't even think about that. Perfect then, we'll switch the language out and call it a day.
