### ISSUE TITLE
Word Probe -- Short

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#154]
The revised design of the study will require implementation of a new probe type, Word Probe--Short. The existing Word Probe will be renamed Word Probe--Long.

**Comment by starakaj** [comment]
So in other words, where normally after you tap on "Words", there's a button that says "Start Word practice", there should be two buttons? "Word probe—short" and "Word probe—long". Is that right?

**Comment by gsuthers** [comment]
Right now just waiting on @tarabyun to send to us

**Comment by gsuthers** [comment]
@starakaj attached is an updated spreadsheet detailing the words to include in each probe and practice (termed "quest"). Short word probe has been added:
[all_stimuli_start_pilot.xlsx](https://github.com/ByunLab/staRt-ionic/files/1273185/all_stimuli_start_pilot.xlsx)

**Comment by gsuthers** [comment]
@starakaj adding a button that says "Word probe short" and one that says "Word probe long" works. We could either do it after you select Syllable or Word, OR we could do it on the same screen to reduce button presses (generally ideal). Below is a mockup of one option. @tarabyun , thoughts?

![probelayout_wordshort-long](https://user-images.githubusercontent.com/11972125/30006160-48602ba6-90c0-11e7-9b6f-069263541884.png)

**Comment by tarabyun** [comment]
@gsuthers, love this mockup! I can give you specific wording tomorrow.

**Comment by tarabyun** [comment]
Description: "Use the quizzes to track your progress over time. You can compare your scores before and after a period of practice."

Syllable quiz: Imitate the clinician's model of syllables containing /r/ (ten syllables, three times each).

Word quiz: Read words containing /r/. The long quiz contains 50 words and the short quiz contains 25 words.

**Comment by starakaj** [comment]
Cool, this looks good to me
