### ISSUE TITLE
Test Probe

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#159]
We've discussed needing to change "Test Probes" to something else. "Test" feels pretty final but sessions often start with it. And "Probe" is a strange word for an app that is primarily used by kids.

**Comment by tarabyun** [comment]
"assessment"? "check-in"? "check level"?

**Comment by tarabyun** [comment]
can we bounce this to slack for Heather's input?

**Comment by gsuthers** [comment]
Will do!
