### ISSUE TITLE
All Quiz pages with wave are aligned above center

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#163]
The screens with a wave in Probes and Quest are off center, pushing the button to begin testing and the words out of view.

![img_0300](https://user-images.githubusercontent.com/11972125/30288542-1a4d8550-96f7-11e7-9ba4-91443e3400ac.PNG)

**Comment by starakaj** [comment]
Hey, not seeing this on my end. I'll have to push an internal 1.0.7 and then get confirmation that this is still an issue

**Comment by starakaj** [comment]
Hey, not seeing this on my end. I'll have to push an internal 1.0.7 and then get confirmation that this is still an issue

**Comment by gsuthers** [comment]
Odd! Let me know when it's pushed and I'll check

**Comment by gsuthers** [comment]
@starakaj Tara and I are both having this issue still.

**Comment by gsuthers** [comment]
iPad Mini 3, iOS 10.3.3

**Comment by gsuthers** [comment]
appears fixed. the transition still shows the bug but it is very brief. fine for now.
