### ISSUE TITLE
Change order of feedback buttons

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#164]
Order of buttons to the right of the wave should be (from top to bottom):

Great
Good
Try Again
Stop Practice
Reset Target

**Comment by starakaj** [comment]
Hey, this is fine, but something that I'm noticing here is that there's now no room for the "hide wave" button. How do we feel about that? Should we get rid of that button?  Make the buttons smaller?

**Comment by gsuthers** [comment]
_copied from slack_
maybe put the button to hide the wave into the upper right corner of the screen, beneath the blue bar that says the header. this way it’s still on the ‘clinician side’ but it is distinctly removed from the other bar… this isn’t super well thought out but I feel like it’s qualitatively different enough that it merits a separation
since you’re augmenting the test… ?

**Comment by gsuthers** [comment]
@helencarey and I can add this to the design tasks we need to address in the next coming months

**Comment by gsuthers** [comment]
No 'hide wave' button is accessible rn so reopening the issue.

**Comment by starakaj** [comment]
Could be wrong, but didn't we decide that the hide wave button was going to be part of the configuration that comes before you begin the actual practice session. 

![image](https://user-images.githubusercontent.com/523270/30928485-c81c8f3e-a389-11e7-85a7-5df0c95c7bde.png)

Maybe it was part of a conversation between Tara and me.

**Comment by gsuthers** [comment]
Ahhh I am so sorry. There it is! Maybe I just didn't see it? Looks great, I'll close it
