### ISSUE TITLE
Syllable Quest should let you choose /r/ types and include trial assessment

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#172]
Right now only the Word Quest selection moves you to a screen where you choose /r/ categories and how many trials to do. We should definitely include the trial selection on both.

**Comment by gsuthers** [comment]
@tarabyun , just want to confirm that:

(A) SLP should be able to choose /r/ categories for Syllable Quests in addition to Word Quest.

(B) Trial Selection should only be available for Quests. Or would you want the SLP to select the # of trials for Quizzes (formerly Test Probes) as well?

**Comment by tarabyun** [comment]
(A) yes
(B) correct, Quests should not have the option to choose /r/ categories.
thanks!

**Comment by starakaj** [comment]
@tarabyun did you mean "**Quizzes** should not have the option to choose /r/ categories.
thanks!"

I ask because this ticket is titled "Quest should let you choose /r/ types" ... so....

**Comment by tarabyun** [comment]
Yes, I meant quizzes...I'm sorry, I am losing track of our terminology :0

**Comment by starakaj** [comment]
Okay, I don't have a CSV for syllables sorted by /r/ types though. Does one exist?

**Comment by tarabyun** [comment]
I think it's a tab in vlookup_all_stimuli_start_pilot, no? (search slack for that file if you don't already have it).

**Comment by gsuthers** [comment]
Here ya go @starakaj , check the Syllables Practice tab.

[vlookup_all_stimuli_start_pilot.xlsx](https://github.com/ByunLab/staRt-ionic/files/1297434/vlookup_all_stimuli_start_pilot.xlsx)

@tarabyun I've noticed there are only ~27 syllables. Just want to make sure that this list is final.

**Comment by tarabyun** [comment]
Yes, this is the correct list. When practice extends through 100 trials, the syllables should just repeat in random order.

**Comment by starakaj** [comment]
Syllables have the same five categories as words?

**Comment by tarabyun** [comment]
yes!

**Comment by starakaj** [comment]
Thanks. I've typed the word consonantal more times today than in the rest of my life combined
