### ISSUE TITLE
Filter Order Slider failing to impact

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#175]
TARA:
I am reasonably confident that changing the filter order slider is no longer having any impact on the wave that is displayed; it appears to be stuck at a low filter order.

it's frankly not such a big issue if users can't adjust it themselves, but if it's going to stay at the same setting for everyone, it should be a higher value

like 35 or so

**Comment by starakaj** [comment]
Oh dip. Something does seem to be up here. Good eye!

**Comment by gsuthers** [comment]
Cool! Will we see this change in .10, .11 or .12?

**Comment by gsuthers** [comment]
@tarabyun please update the app and test this.

**Comment by tarabyun** [comment]
it works!
