### ISSUE TITLE
Profiles are still deleted automatically, sometimes.

### ISSUE THREAD

**Issue by awanderingorill** [ByunLab/staRt-ionic#210]

**Comment by starakaj** [comment]
From the tester:

"Profile deletion issue continues. It stopped for a while when I exported all audio recordings, but started happening again shortly after. There are probably a few recordings that got deleted from the profile before they were uploaded."

**Comment by starakaj** [comment]
Okay, so the root of this issue is that we were storing profiles in local storage, which the OS can purge basically whenever it feels like it. This is no longer the case—everything is in firebase now. So this bug _should_ be fixed as soon as we make the Grand Update to Firebase.

**Comment by jonathan-chin** [comment]
should we close the issue then?

**Comment by starakaj** [comment]
yes
