### ISSUE TITLE
The short word quiz has only prevocalic /r/ and /ar/

### ISSUE THREAD

**Issue by awanderingorill** [ByunLab/staRt-ionic#212]
![](https://files.slack.com/files-pri/T0PPJ06PK-F9N0EAKA8/image.png)

**Comment by starakaj** [comment]
I don't know if this is a bug or not... Can't remember what /r/ types that mode is meant to support. Worth taking a peak at the code @jonathan-chin (words_controller.js and words_template.html) if the code is doing what it expects to do. Also worth pinging Tara @awanderingorill to see if this is expected.

**Comment by jonathan-chin** [comment]
The Short Word Quiz seems to only load data from Word_Probe.csv. Is this the correct data set to load?

as an aside, it also seems to load the file twice, which produces a final word list of:

```["raw","rug","rock","wrong","rose","robe","run","rules","rude","rob","read","ring","rake","raft","red","wrap","race","reach","rip","ride","scarf","dark","star","farm","barn","share","chair","stare","scare","tear","weird","cheer","year","clear","beard","fork","board","door","floor","sword","stir","sir","worm","turn","nurse","ladder","flower","butter","hammer","mother","raw","rug","rock","wrong","rose","robe","run","rules","rude","rob","read","ring","rake","raft","red","wrap","race","reach","rip","ride","scarf","dark","star","farm","barn","share","chair","stare","scare","tear","weird","cheer","year","clear","beard","fork","board","door","floor","sword","stir","sir","worm","turn","nurse","ladder","flower","butter","hammer","mother"]```

there are duplicates and reduces to just one instance of Word_Probe.csv

**Comment by tarabyun** [comment]
We were unable to reproduce this bug.
