### ISSUE TITLE
Long word quiz: prompt says "Would you like to upload this quiz [object Object] session?" during formal testing

### ISSUE THREAD

**Issue by awanderingorill** [ByunLab/staRt-ionic#213]
What's up with the "[object Object]"?

**Comment by jonathan-chin** [comment]
this is due to sessionDisplayString() in practice_directive_controller line 129

caused by the stats variable. I'm unsure what the final desired popup to look like, likely without the `stats` variable there. however, removing it could cause unseen issues elsewhere

**Comment by starakaj** [comment]
Ah okay, this is my bad. Should be printing using `session` but was using `stats` instead.
