### ISSUE TITLE
Add an app version indicator

### ISSUE THREAD

**Issue by starakaj** [ByunLab/staRt-ionic#219]
It would be really nice if there were some persistent indicator in the app that would let users know what version there were currently running.

**Comment by jonathan-chin** [comment]
definitely a good idea. Share Meals has version, environment, and platform tagged in the menu.

I propose adding it on the Profiles page, in small print, on the bottom. need to know what the current version number is.

**Comment by starakaj** [comment]
Okay, I went ahead and added this to the Resources page. Should be fine for debugging.
