### ISSUE TITLE
Word Quiz Upload Prompt Reads "Null"

### ISSUE THREAD

**Issue by awanderingorill** [ByunLab/staRt-ionic#223]
Prompt to upload a word quiz reads "Would you like to upload this word quiz null session?" Should not have "null" in it. Need to check if it happens for other quiz and quest types; need to know if there are conditions in which "null" does not appear.

**Comment by jonathan-chin** [comment]
what is the expected output? what should the prompt look like?

should null be removed altogether? should it be another word?

**Comment by cmsava1897** [comment]
Hi all, 

I think this was fixed because I cannot reproduce the bug. 

Christian
