### ISSUE TITLE
Partial recording bug

### ISSUE THREAD

**Issue by jonathan-chin** [ByunLab/staRt-ionic#227]
If a quest (and possibly others) is started but the page is navigated away from, the app still has a record of a partial recording. When trying to upload this, an error is thrown from server.

To reproduce:
1) hit quest
2) start word quest
3) select any /r/ categories
4) don't complete quest; instead click on Profiles before finishing

The list of recordings has a new entry marked as not uploaded.
It doesn't have a time stamp like a regular, completed recording has.
When trying to upload, server will throw an error.

Expected behavior:
either the recording is never saved (since it's incomplete)
or a popup shows up before navigating away from quest, asking if the user wants to upload
or necessary metadata is edited so the unfinished recording can upload successfully

**Comment by helencarey** [comment]
This seems to be resolved.

**Comment by Tjc10** [comment]
I found this bug to be the same as bug #273.  Please let me know if I have interpreted the description of this bug wrong.  My findings are the same as #273 but I can retest if my understanding of this ticket is in error --- In terms of this issue, I tested 1/2 sesssion, exited and tried to resume session using profile "tc" (version 2.0.10). I used formal test mode and went through the usual baseline/tutorial/play, play and started first session successfully. When I exited this first session 1/2 way (session was a non-BF) and tried to resume, the app literally froze in an undecided kind of mode. Image below. It did not show tokens/words/nothing that usually appears when you are in test mode. The screen was essentially blank (kites/birds visible but no words/tokens etc.). I exited and went back to profile. Clicked on stop session. Exited the app entirely. Re-entered the app and hit start in the profile "tc" --- the app prompted me appropriately. I went to play. It asked if I wanted to resume the session but when I hit "resume" and was brought back into the session, the app essentially froze again (same screenshot below appeared a 2nd time). I repeated exiting again and re-entering again but ended back on the "frozen" screen a 3rd time. App does not allow me to resume after testing 1/2.
![image](https://user-images.githubusercontent.com/51724845/63308609-7346b080-c2c1-11e9-80ba-39ebb602ba2e.png)

**Comment by helencarey** [comment]
Closing b/c this is the same as bug #273.
