### ISSUE TITLE
ratingChange event not fired every 10 ratings

### ISSUE THREAD

**Issue by starakaj** [ByunLab/staRt-ionic#230]

**Comment by starakaj** [comment]
I can't actually reproduce this. Are the steps to reproduce as simple as going to quest and tapping a rating 10 times?

**Comment by jonathan-chin** [comment]
Yes. If you look the visual feedback feature, a coin doesn't get appended every 10th click.

**Comment by starakaj** [comment]
What branch are you on?

**Comment by jonathan-chin** [comment]
Should happen as early as adaptive difficulty branch

**Comment by starakaj** [comment]
Have you pushed this branch? I'm on `quest-progressive-difficulty-wordlist`
and I don't see anything...

-S

**Comment by jonathan-chin** [comment]
potentially just a browser development issue. doesn't seem to happen on simulator and devices. in this case, it is not a problem.

**Comment by jonathan-chin** [comment]
fixed
