### ISSUE TITLE
Add colored sand dollars along bottom as words are rated (sand holes)

### ISSUE THREAD

**Issue by starakaj** [ByunLab/staRt-ionic#233]
See https://docs.google.com/document/d/1BdJTFadMCk2H-cm9lbbMQGDfIMMuwTpj07rjHIR4Dpc/edit#heading=h.vc46a0jl7ml

Page 3: When taking a word/syllable quest, we should see color-coordinated sand dollars appearing along the bottom of the screen.

**Comment by starakaj** [comment]
Jon, assigning this one to you, since I know you've been working on some stuff related to this.

**Comment by jonathan-chin** [comment]
progress made. css is just temporary now; we can finalize it once the rest of the visual images are in place.

![image](https://user-images.githubusercontent.com/7519412/45645898-df0c1200-ba8f-11e8-9f79-f342119fdca7.png)

**Comment by starakaj** [comment]
Implemented on master, thanks Jon
