### ISSUE TITLE
Implement transparent background wave

### ISSUE THREAD

**Issue by starakaj** [ByunLab/staRt-ionic#236]
See https://docs.google.com/document/d/1BdJTFadMCk2H-cm9lbbMQGDfIMMuwTpj07rjHIR4Dpc/edit#heading=h.vc46a0jl7ml

Page 3: The LPC wave should be white and transparent, so that the ocean can be seen behind it. The design doc shows the wave extending beyond the left + right posts, but that's not necessary right away.

**Comment by starakaj** [comment]
@helencarey What's the status here? Wave looks transparent on master.

**Comment by helencarey** [comment]
Yup, its closed.

**Comment by jonathan-chin** [comment]
not sure if this is the correct thread but I noticed a conflict. the coins are too close to the wave and get hidden behind. only first 7 coins are displayed, then the last 3 get hidden behind the sand under the wave.

likely fixes are either increase z-index of coins or move coin set down.

(coin == sand dollar?)

**Comment by helencarey** [comment]
@jonathan-chin 
Hi Jon. Yup, I see what you are saying. The sand portion of the lpc-slider sketch occludes the top of the coin stacks. 

If you can, just move the coin stacks down. Increasing the z-index of the coin stacks would block the raycaster on the lpc sketch, which allows you to move the starfish, so we should avoid that.

If you want, I can take a look at this tomorrow.

**Comment by jonathan-chin** [comment]
Helen, I think you might get a chance to look at it before I do.

**Comment by helencarey** [comment]
@jonathan-chin OK, I'll try a short term fix tomorrow.

@starakaj a better long term solution may be to move the coin rows to the lpc-directive, where I could layer them below the slider and ratingBtn planes.  

Granted, I don’t know how everything is wired up, but I assume we a going for something like: the lpc-directive’s primary responsibility is to draw things to the screen (wave, starfish, coins), and the practice-directive’s primary responsibility is the game logic (serving up words, recording the score, etc). If this is the case, lets discuss when we are both back in the office.

**Comment by starakaj** [comment]
Maybe a dumb question, but does the wave need to draw sand? Couldn't we just skip that and avoid clipping the coins?

**Comment by starakaj** [comment]
Looks good to me. For future reference, if you want me to test something, you should assign it to me :)
