### ISSUE TITLE
Update the Star Slider, the target fz on signpost, and Reset Target button per new design

### ISSUE THREAD

**Issue by starakaj** [ByunLab/staRt-ionic#242]
See https://docs.google.com/document/d/1BdJTFadMCk2H-cm9lbbMQGDfIMMuwTpj07rjHIR4Dpc/edit#heading=h.vc46a0jl7ml

Page 3: The current LPC target should be written on a post next to the wave.

**Comment by helencarey** [comment]
@starakaj 
branch: hmc/lpc-directive-beachScene
**ISSUE:  Saving User-Placed Target F3s**
  
In the lpc-directive_controller, we are updating the user’s Target F3 via the ProfileService onTouchMove. This creates creates a LOT of fb 400 errors (client error)
<img width="1343" alt="screen shot 2019-03-07 at 4 42 35 pm" src="https://user-images.githubusercontent.com/8650944/53992045-dcfb4580-40f9-11e9-85f4-cc9eb7d48806.png">

In the current branch this code is at lines 338-341.
Its called from the animate loop (60fps) when targetNeedsUpdate is true (trigger = slider onTouchMove), so maybe we are just be slamming the ProfileService/firebase with data.

When I moved the code to be triggered by the slider’s onTouchEnd (ln 226-232), I got fewer errors - sometimes no errs; but I’m not sure if we are saving 100% of the time. (Often the value would reset when I navigated to another page and back.)

**My questions are: What is this process supposed to do, like what is the end goal? 
And what should I test for?**

Do we just need to save the last slider location before the user ends the session? (save ui state)
Is this intended as an ‘undo btn’ in case someone accidentally moves the slider?
Or is this an important piece of session data, like we need a saved record of where the slider was to match w/ audio or rating timestamps?


n.b. These fb errors would happen before I started working on this branch, so maybe they aren't actually indicative of a problem, the transactions will eventually complete, and everything is totally fine. 

anyway, pls advise.

**Comment by helencarey** [comment]
**Questions for @erinmdoty** 
changes affect: Free Play & Quest-BF

- [ ] Star slider, frequency signpost, and Reset Target button should appear as below.
- [ ] Slider should behave as expected — responds to touch, doesn’t lag, etc.
- [ ] Fz signpost should always show a the value of the slider position on the 0-4500 hz wave graph.
- [ ] The Reset Target button behaves as expected — responds to touch, runs the ‘lookup default F3’ process on user profile, updates the slider position accordingly.

--------
**vQA** 
Current Version (2.0.2)
![242](https://user-images.githubusercontent.com/8650944/54566857-6e936e80-49a8-11e9-97b5-fca4b3b1b2cd.PNG)

Next Version
![Simulator Screen Shot - iPad Air - 2019-03-18 at 17 47 37](https://user-images.githubusercontent.com/8650944/54566877-7ce18a80-49a8-11e9-8e81-f552b56e966d.png)
