### ISSUE TITLE
Unable to upload recordings stored in profile

### ISSUE THREAD

**Issue by erinmdoty** [ByunLab/staRt-ionic#248]
After creating recordings that did not upload, I am also unable to upload those recordings from the recordings list in the participant profile. 

I click on a recording, click the blue "upload" button, and then receive an error message 4 times as the screen gets progressively darker. After clicking on it 4 times I can see the normal profile screen again. However, the "upload" button is now greyed out and underneath it it says "Uploading...". Even after waiting a while this does not change unless I exit the profile and re-enter.

Running version 1.0.25 of staRt on iPad 4th generation (AI1458) with iOS 10.3.3

**Comment by starakaj** [comment]
Seems like this was related to the server being down? @erinmdoty, would you mind trying this again and verifying that it's still an issue? I can't reproduce on my end.
