### ISSUE TITLE
p01s5: Hide screen introducing sand bank

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#254]
https://app.asana.com/0/663025469639222/815325998197426/f

**Comment by helencarey** [comment]
@tarabyun  Hi Tara, what do you think of modifying this slide, instead of removing it (see below). 

The focus of the modified slide is to explain how to **navigate** b/t sections in the Tutorial, rather than introducing the sandbank, which doesn't exist yet. 

<img width="1299" alt="screen shot 2018-10-26 at 5 55 33 pm" src="https://user-images.githubusercontent.com/8650944/47594618-2ff20e80-d94a-11e8-95d9-b9bccad610fd.png">

**Comment by tarabyun** [comment]
This looks good, but do the sand dollars actually work for navigation? I didn't think that was something that had been implemented.

**Comment by starakaj** [comment]
Hey @helencarey , what's the status of this ticket? Should I be testing this? Should @erinmdoty ?

**Comment by helencarey** [comment]
@tarabyun This branch has the p01s5 slide that looks like this. It is ready to merge, if we choose to go this route. Tara, I will write you an email about the tutorial navigation, which should definitely work, but is probably confusing/not intuitive to users as is.

![simulator screen shot - ipad air 2 - 2018-10-30 at 16 56 29](https://user-images.githubusercontent.com/8650944/47750559-072d8a00-dc66-11e8-8d64-ccaec3eba606.png)
