### ISSUE TITLE
p05s2: In screen with text "The bottom picture is a good /r/. It sounds like errr," add text "(rhymes with 'her')"

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#255]
https://app.asana.com/0/663025469639222/815325998197425/f

**Comment by helencarey** [comment]
@tarabyun - Simulator screenshot. Pls review. 

![gh255](https://user-images.githubusercontent.com/8650944/47592429-4ba4e700-d941-11e8-9dda-be4625bb0a7a.png)

**Comment by tarabyun** [comment]
thumbs up!

**Comment by starakaj** [comment]
@helencarey I don't think this is on master, maybe it's hiding on another branch?
