### ISSUE TITLE
p05s3a: Add screen with different options for appearance of /r/

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#256]
https://app.asana.com/0/663025469639222/815325998197427/f

**location:** After slide ending with "See how the 3rd peak aligns with the target in the 'Good R' image?" 

**design:** Include image of single-peak /r/. Create graphics based on image files from Erin.

**copy:**
Sometimes the 2nd and 3rd peaks move so close together that they look like just one peak. 

If you see just two peaks for /r/, focus on getting the second peak below the white dotted line.

**Comment by helencarey** [comment]
@tarabyun For the text "If you see just two peaks for /r/, focus on getting the second peak below the white dotted line."  
We should probably say 'to the left of' instead of 'below,' right?

**Comment by tarabyun** [comment]
Yes! Or maybe even 'close to'?

**Comment by helencarey** [comment]
@tarabyun  1st Draft
<img width="681" alt="screen shot 2018-10-26 at 4 00 37 pm" src="https://user-images.githubusercontent.com/8650944/47589853-73dc1800-d938-11e8-869c-e265c136dd94.png">

**Comment by helencarey** [comment]
@tarabyun - Simulator screenshot. Pls review.

![gh256](https://user-images.githubusercontent.com/8650944/47592465-6bd4a600-d941-11e8-8c4a-6b3f98efba74.png)

**Comment by tarabyun** [comment]
Text changed back to "below" instead of "close to"--can we return to "close to"? Otherwise, good to go.
