### ISSUE TITLE
p05s5: Update final screen of tutorial

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#257]
https://app.asana.com/0/663025469639222/815325998197431/f

**copy:**
Replace "Your SLP will set a target line by moving the starfish on the beach" with text "The app will suggest a target for you based on your age." 

"You or your SLP can move the target further to the left for a more challenging target--but don't go further than about where you see the starfish in this picture." 

**design:** 
Replace pic with screenshot of free play screen with starfish cursor at (around) 1550

**Comment by helencarey** [comment]
@tarabyun - Simulator screenshot. Pls review.
![gh257](https://user-images.githubusercontent.com/8650944/47592741-8eb38a00-d942-11e8-8e63-fd47be313d3a.png)

**Comment by tarabyun** [comment]
There had been additional requests for this slide in the Design Asana:

Add text (after "for your age."): "You or your SLP can move the target further to the left for a more challenging target--but don't go further than about where you see the starfish in this picture."  

Replace pic with screenshot of free play screen with starfish cursor at (around) 1550

I think Erin provided a screenshot with the cursor at around that point. Do you have it, and could these changes be implemented?

**Comment by helencarey** [comment]
@tarabyun   oh geez. Here is the correct fix/screenshot.
@Sam the branch is 'hmc/tutorial-fix-257.' 
This should be ready to merge once Tara approves the 

![simulator screen shot - ipad air 2 - 2018-10-30 at 15 30 24](https://user-images.githubusercontent.com/8650944/47745281-b152e500-dc59-11e8-91a0-90e4b811a80d.png)

**Comment by tarabyun** [comment]
brilliant! approved!

**Comment by helencarey** [comment]
Great!  I had to remove the second paragraph, which said 'You will practice matching your wave’s 3rd peak to the target;' but I assume that instruction should be obvious by this point in the tutorial.
