### ISSUE TITLE
Clean up Profiles page

### ISSUE THREAD

**Issue by tarabyun** [ByunLab/staRt-ionic#266]
Myriad small bugs. Male and Female are ellipsed, for example

**Comment by starakaj** [comment]
Helen, if you have a chance in the next couple days to look at this, that would be so rad. The profiles page has always been a problem child, and unfortunately it's always gotten short shrift. It doesn't have to be sexy, but I'd love if we could address some basic usability bugs. Want to take a stab?

**Comment by helencarey** [comment]
Addressed by #293. 
Update to Profiles interface is ready for testing.

**Comment by starakaj** [comment]
This is amazing news!! I'll test myself and then spin up a new version.

-S

**Comment by helencarey** [comment]
😊 but it aint perfect.... 😬

working on some little fixes now.

-h

**Comment by starakaj** [comment]
Looks great to me. I'm going to assign this to @erinmdoty, in case she wants to weigh in, but otherwise I'm ready to call this closed.
