### ISSUE TITLE
Never see biofeedback (always non-biofeedback)

### ISSUE THREAD

**Issue by tarabyun** [ByunLab/staRt-ionic#269]

**Comment by starakaj** [comment]
Seems like for some reason, the automated testing schedule always chooses non-biofeedback. Possibly the randomized assignment code is broken

**Comment by starakaj** [comment]
```
    this.biofeedback = biofeedback.pop();
    this.biofeedback = "TRAD";
```
Looks like I left in some debugging code, that forces the schedule into the traditional paradigm
