### ISSUE TITLE
level 4 of adaptive difficulty not drawing words randomly in word quest

### ISSUE THREAD

**Issue by erinmdoty** [ByunLab/staRt-ionic#272]
In word quest, when in adaptive difficulty level 4 (different words in the same carrier phrase), words should be chosen randomly from levels 1-3. Instead, they are being chosen in blocks of 10 from one level at a time. For example, in the carrier phrase "Say [word] to me", in the first 10 trials, [word] is from the level 2 list. In the next 10 trials, [word] is from, say, the level 3 list. It continues like this, changing every 10 trials. 

I think the intended behavior for level 4 of adaptive difficulty is that from trial to trial, [word] should be randomly chosen from the lists from levels 1-3.

**Comment by erinmdoty** [comment]
Running version 1.0.26 of staRt on iPad 4th generation (AI1458) with iOS 10.3.3

**Comment by starakaj** [comment]
Need to find out if this is still an issue.

**Comment by starakaj** [comment]
Testable in v1.0.32

**Comment by jonathan-chin** [comment]
Sorry I've been slacking. Will look into this.
