### ISSUE TITLE
Does the Within-Session Saving feature meet its acceptance criteria?

### ISSUE THREAD

**Issue by erinmdoty** [ByunLab/staRt-ionic#273]
### Original issue title: when exiting app during a quest, progress is not saved

If, part way through a quest, I leave the app and then re-enter, I am not able to start up from where I left off, mid-quest. I have to start the quest over. I think the intended behavior is that if I have to leave a quest part way through (say, at trial number 30), I should be able to pick up right at trial number 31 in the same quest the next time I enter that particular profile. 

It would be ideal to have a "save progress and return later" button, because clinicians will often have to stop a quest part way through (maybe the therapy session time is up, or the child gets distracted).

**Comment by erinmdoty** [comment]
Running version 1.0.26 of staRt on iPad 4th generation (AI1458) with iOS 10.3.3

**Comment by helencarey** [comment]
The acceptance criteria list is in Tara's workflowy, under 'Feature testing assignments/Acceptance criteria for within-session saving feature'

**Comment by Tjc10** [comment]
In terms of this issue, I tested 1/2 sesssion, exited and tried to resume session using profile "tc" (version 2.0.10).  I used formal test mode and went through the usual baseline/tutorial/play, play and started first session successfully.  When I exited this first session 1/2 way (session was a non-BF) and tried to resume, the app literally froze in an undecided kind of mode.  Image below.  It did not show tokens/words/nothing that usually appears when you are in test mode. The screen was essentially blank (kites/birds visible but no words/tokens etc.).  I exited and went back to profile. Clicked on stop session.  Exited the app entirely. Re-entered the app and hit start in the profile "tc" --- the app prompted me appropriately. I went to play.  It asked if I wanted to resume the session but when I hit "resume" and was brought back into the session, the app essentially froze again (same screenshot below appeared a 2nd time).  I repeated exiting again and re-entering again but ended back on the "frozen" screen a 3rd time.  ***App does not allow me to resume after testing 1/2.***
![image](https://user-images.githubusercontent.com/51724845/63308341-3b8b3900-c2c0-11e9-9685-6b4cd09cc3a8.png)

**Comment by helencarey** [comment]
Yikes! Thanks @Tjc10. @WillHaack is working on 2.0.11 now with a fix for the upload issue. We' look at this again in 2.0.11, before sending it back to you.

**Comment by tarabyun** [comment]
Just doing a bit of informal testing and got an error when attempting to resume Quest mode: "No profile Can't start word quest bio BF-1--create a profile first." Immediately before this, I was on the page with settings for Quest and had attempted to change the target (but was denied, correctly, with a message that you can't change settings mid-session)--not sure if that's what caused the No profile error. When I dismissed the error message and went to the Profiles page, it was empty--had to quit out of the app.

**Comment by helencarey** [comment]
@tarabyun Thanks for the feedback. I've encountered similar quirks. 
They are tricky to troubleshoot because these errors don't always occur.

This type of bug is probably related to the timing of when the profile (firebase) information arrives or is incorporated during page/activity loads. I have several ideas about how to better control this process, but haven’t had a chance to fully research the issue yet.
