### ISSUE TITLE
Remove data from practice-directive_controller

### ISSUE THREAD

**Issue by starakaj** [ByunLab/staRt-ionic#275]
At then end of practice-directive_controller, we've got several hundred lines of data. Could we move this to a JSON file? Loading that file asynchronously isn't necessarily an issue, and I wouldn't mind loading it synchronously either

**Comment by helencarey** [comment]
Hey @jonathan-chin, I was considering doing a little housecleaning in the Practice Directive in preparation for some upcoming graphic+practice directive tasks. You have a note in the code about not removing the word lists to avoid async loads issues.

Do you remember when/how these async load issues occurred? Were you previously fetching word and phrase arrays from firebase?
Anyway, I was thinking about sticking the word list into a '[Factory Provider](https://code.angularjs.org/1.4.3/docs/guide/providers)' which is just a barebones Service, but wanted to discuss with you first.

**Comment by helencarey** [comment]
the dev on this is done, but it is in branch hmc/practDir-gameScoring, which is not yet ready for merge.

**Comment by WillHaack** [comment]
Done by @helencarey here

https://github.com/ByunLab/staRt-ionic/commit/1a2322908ba732cc41c357bc41d617b7e0953e64
