### ISSUE TITLE
Profiles page not showing "Female" and "Male"

### ISSUE THREAD

**Issue by erinmdoty** [ByunLab/staRt-ionic#287]
On the profiles page, the options "Female" and "Male" are not completely visible.

![img_0050](https://user-images.githubusercontent.com/42744629/48284999-3777e400-e42f-11e8-8ea5-732223258d2c.PNG)

Running version 1.0.30 of staRt on iPad 4th generation (AI1458) with iOS 10.3.3

**Comment by starakaj** [comment]
Falls under the purview of Helen's profiles work.

**Comment by helencarey** [comment]
yup, this will be fixed in the next update.

**Comment by helencarey** [comment]
Addressed in #293.
The Male/Female options are visible and functioning, but the underlying problem is still there. (Those 2 inputs btns keep evading my styles. I will address this in a different styles-related ticket.)

**Comment by starakaj** [comment]
This looks much better in any case, and definitely fixes the stated ticket
