### ISSUE TITLE
Total accuracy in "All done" prompt goes to 14 decimal places 

### ISSUE THREAD

**Issue by erinmdoty** [ByunLab/staRt-ionic#290]
After finishing the 8 pilot-tester sessions, the "All done" prompt shows total accuracy to 14 decimal places. I'm guessing this is an error, as the same prompt shows the final session accuracy to only one decimal place.

![img_0047](https://user-images.githubusercontent.com/42744629/48285803-bbcb6680-e431-11e8-86c0-4a64bda3e848.PNG)

Running version 1.0.30 of staRt on iPad 4th generation (AI1458) with iOS 10.3.3

**Comment by starakaj** [comment]
Ha! What, you've got a problem with that much accuracy!? Kidding.
