### ISSUE TITLE
"All done" prompt sometimes comes up too soon

### ISSUE THREAD

**Issue by erinmdoty** [ByunLab/staRt-ionic#291]
When going through the 8 pilot-tester sessions, the "All done" prompt sometimes comes up when I have completed fewer than 8 sessions. This seems to happen when I have exited some of those sessions before completing them. Note that the prompt telling me what number session I am about to start is correct, though. 

Example: I exit part way through and re-enter during a few of my sessions. When I open the profile to complete my 5th session, I receive the prompt asking me if I would like to finish session 5. This is correct. I do the session, and when I finish, I receive the "all done" prompt. The "all done" prompt seems to be triggered by going in and out of sessions 8 times, rather than by completing 8 whole sessions.

Running version 1.0.30 of staRt on iPad 4th generation (AI1458) with iOS 10.3.3

**Comment by starakaj** [comment]
Hey, I'm sorry but I don't quite understand what's happening here, and I can't reproduce this myself. Are there any steps you can go through to reproduce this bug consistently?

**Comment by erinmdoty** [comment]
I see that this has been moved to "to do in v1.0.32" so you are probably aware, but just wanted to mention that this happened when testing v1.0.31 as well. This time, after going through six of the eight quests (without leaving any half-way through), the message "all done - congratulations, you finished your 8 quests" came up.

Running version 1.0.31 of staRt on iPad 4th generation (AI1458) with iOS 10.3.3
![img_0053](https://user-images.githubusercontent.com/42744629/49389960-990d3480-f6f5-11e8-89d1-a1545ec09a33.PNG)

**Comment by starakaj** [comment]
Should be testable in v1.0.32
