### ISSUE TITLE
Make AWS crontab work again

### ISSUE THREAD

**Issue by starakaj** [ByunLab/staRt-ionic#292]
The crontab got wiped when I restarted the server. So I should fix that I guess.

**Comment by jonathan-chin** [comment]
Wait. How does a crontab get wiped?

**Comment by jonathan-chin** [comment]
No, crontab should persist. One thing to remember is if you're looking at the crontab for the ec2 user or the root user. They are separate. I believe we have everything on the ec2 user

**Comment by starakaj** [comment]
I'm not sure what's going on exactly, but if you ssh into ec2-user and open up the crontab, it's empty. Further, it looks like our old cronjob isn't running. Files I uploaded yesterday are still sitting in GridStore.

**Comment by helencarey** [comment]
@jonathan-chin Hi Jon, should we close this issue? Did this get resolved? (I don't have access to any of the aws stuff, so I can't just check it.)

**Comment by jonathan-chin** [comment]
Yes I believe so
