### ISSUE TITLE
Profiles > Drawer: On load everything (all student names) appears as selected.

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#302]
Need to figure out what is going on w/ the ion-radio selected display.

**Comment by helencarey** [comment]
@erinmdoty Did you ever have this issue?

**Comment by helencarey** [comment]
This is a weird one. I've seen this happen before, but it's rare -- like, maybe 10% of the times that I open the app after completely quitting it. I can NOT reproduce it on purpose - ugh.  This is what it looks like:
<img width="702" alt="screen shot 2018-12-11 at 1 15 04 pm" src="https://user-images.githubusercontent.com/8650944/49883625-1ecd6600-fe01-11e8-9927-b8f3b544ad74.png">

@starakaj  Any idea why this would happen? Should we worry about it?

**Comment by helencarey** [comment]
@starakaj If this isn't indicative of a problem, then an easy fix would be to just overwrite the default ion-styles for the selected items. Like this mock:
![drawer-selection](https://user-images.githubusercontent.com/8650944/49883933-aa46f700-fe01-11e8-9c82-235fb9f5762b.gif)

**Comment by erinmdoty** [comment]
@helencarey Hmm, no, I haven't had this happen.

**Comment by starakaj** [comment]
I've never seen this happen either
