### ISSUE TITLE
keyboard obscures form when creating new profile

### ISSUE THREAD

**Issue by erinmdoty** [ByunLab/staRt-ionic#309]
When creating a new profile, the keyboard that pops up obscures most of the form (except for the name field), so the user has to close and re-open the keyboard to see the age and height fields, and I think the only way to fill out these fields is to have the keyboard open over them (so the user can't actually see what's being typed into the field while typing). Is it possible for the keyboard to come up lower on the screen, or for the form to move up on the screen while the keyboard is there so the form is visible while the user fills it out? 
![img_0052](https://user-images.githubusercontent.com/42744629/49390401-dc1bd780-f6f6-11e8-8812-5e81a12b3060.PNG)

Running version 1.0.31 of staRt on iPad 4th generation (AI1458) with iOS 10.3.3

**Comment by helencarey** [comment]
Hey @erinmdoty ,
I'll have to look into this.

The viewport will move to keep the input field in view when the keyboard is docked.
(If its not doing this, lmk. A docked keyboard should look like the pic.)
![img_0118](https://user-images.githubusercontent.com/8650944/49397356-53f2fd80-f709-11e8-94d5-e605b96a9d1e.PNG)

Once the keyboard is split, things don't always behave a expected. I'll have to see if there is anything we can do about this from w/in our framework.
![unadjustednonraw_thumb_3d2e](https://user-images.githubusercontent.com/8650944/49397565-f6ab7c00-f709-11e8-9214-002c129c3784.jpg)

If not, maybe @starakaj knows how folks do this:
![unadjustednonraw_thumb_3d2f](https://user-images.githubusercontent.com/8650944/49397817-aed92480-f70a-11e8-8b94-700013cea817.jpg)

**Comment by erinmdoty** [comment]
@helencarey  Confirming that there is no problem when the keyboard is docked - only when it is split.

**Comment by helencarey** [comment]
Thanks, @erinmdoty!  

@tarabyun @starakaj what do you think?
I suspect the split keyboard is a feature that only a few folks use. At this point, I'd say let's leave it and see if it crops up again in the bug list. We can always instruct users to dock the keyboard. 

There are several cordova keyboard plugins. I didn't spend much time researching this, but it didn't seem like there were any that address this specific issue.
https://cordova.apache.org/plugins/?q=keyboard&platforms=cordova-ios

**Comment by tarabyun** [comment]
This isn't a huge deal, so it's OK to leave in for this version release. However, is there a way to make the keyboard docked by default, avoiding the issue?
