### ISSUE TITLE
Troubleshoot 'filter order' code in Profiles controller

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#312]

**Comment by helencarey** [comment]
hey @starakaj,

Pls, checkout hmc/profiles-filterOrder. 
The profiles controller could use your attention.

I'm getting this at start up:
<img width="399" alt="screen shot 2018-12-05 at 4 52 45 pm" src="https://user-images.githubusercontent.com/8650944/49553296-1509a700-f8c5-11e8-8e81-6e3cecc94400.png">

And I don't think any filter order adjustments are getting written to the profile.
I get a bunch of 400s when I drag the slider, which should update the filter order:
<img width="631" alt="screen shot 2018-12-05 at 7 33 53 pm" src="https://user-images.githubusercontent.com/8650944/49553384-6ca81280-f8c5-11e8-832b-8fe75670b03d.png">

**Comment by starakaj** [comment]
I actually can't reproduce this, even on that branch, and my filter order seems to save correctly. I wonder if we've got a different version of webkit or something?
