### ISSUE TITLE
Odd text in Free Play (see desc.)

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#338]
Hey @helcat, one of our pilot testers notified me that the text "It's just you and the wave" still shows up in free play mode even when a formal pilot tester is in traditional treatment mode and the wave is hidden :joy:  Could we change that? Maybe in both conditions, the text should read "This is the place to practice your /r/ sounds on your own. There are no prompts or words to match here--just try all different things and see what works best."

per TM: version is 2.0+.....I think 2.0.3?

**Comment by helencarey** [comment]
@tarabyun 

I will update the Free Play screens to look something like this:
![fp-NoProtocol](https://user-images.githubusercontent.com/8650944/60824584-d9df9700-a177-11e9-925b-b643c817eedc.png)


![fpNoBF](https://user-images.githubusercontent.com/8650944/60824595-de0bb480-a177-11e9-9e1f-b046d4bc7965.png)

**Comment by tarabyun** [comment]
Awesome, thanks! For some reason the spacing looks a bit wonky to me--probably something you were going to fix anyway, but I thought I'd mention it.

**Comment by helencarey** [comment]
Ok, implemented. Here are the simulation screenshots. 
I tried styling it several ways, and thought the text in 1 block at the bottom looked best.

![Simulator Screen Shot - iPad Air 2 - 2019-07-08 at 15 29 58](https://user-images.githubusercontent.com/8650944/60837196-9bf16b80-a195-11e9-98b2-93ebf7df2a43.png)

![Simulator Screen Shot - iPad Air 2 - 2019-07-08 at 15 30 48](https://user-images.githubusercontent.com/8650944/60837211-a27fe300-a195-11e9-8c30-d239125d3ea1.png)

**Comment by tarabyun** [comment]
Looks great!

**Comment by helencarey** [comment]
**QA @Tjc10 ** 
QA testing is the same as #346.
When you close #346, please close this issue too.

**Comment by Tjc10** [comment]
Odd text no longer appears in free play.  The updated text appears in free play scenarios (see text notes entered on ticket #346)
