### ISSUE TITLE
Add the email address of the clinician to the session metadata

### ISSUE THREAD

**Issue by starakaj** [ByunLab/staRt-ionic#339]

**Comment by starakaj** [comment]
Should be fixed in 2.0.4.

**Comment by starakaj** [comment]
You can test this by uploading a recording in 2.0.4, then looking at the server to verify that the recording metadata correctly contains the email. Let me know if you upload something and I'll check the server.

**Comment by erinmdoty** [comment]
@starakaj I've uploaded a ton of recordings today, but haven't been able to access the server to check. The email address associated with my staRt account is either mine (erinmdoty@gmail.com) or it's drcgongora@gmail.com. Can you check to see if the recording metadata correctly contains the email?

**Comment by helencarey** [comment]
Hey @erinmdoty, Sam's last day of development was this past Friday, so we are going to start sending server related questions to @jonathan-chin. Is this something you will be able to verify on your own later, or should we ask @jonathan-chin to look in to your uploads?

**Comment by erinmdoty** [comment]
I don't have server access so if @jonathan-chin can look at it that would be great!

**Comment by helencarey** [comment]
@erinmdoty Was this ever resolved?

**Comment by Tjc10** [comment]
Hi Helen, I believe this is the 2nd of two Erin assignments. Can you share the link to the server? I have never accessed it before. I can check if email issues show up for me; as Erin reports above.  Thanks.

**Comment by helencarey** [comment]
@tarabyun @jonathan-chin  See Erins q above.  I actually don't have a link or login info to this server either. This is the amazon-hosted database that hosts the uploaded research data (not firebase, which handles login, in-app progress, etc)

**Comment by helencarey** [comment]
Hey @WillHaack 
I just kicked this one to you. I’m not sure I understand the initial request. 
(possibly, referencing something in the audioPlugin — like the firebase user’s email should be getting included in files output by the AudioPlugin???)  
a la this commit  4ef177cae164e7f0d9ee8faa79412e1ea3d5975d
and this one 40f0676642f1e012db7f02e850ae7cb1ecc7bc62

The ticket history makes it seem like Sam completed the fix, we just didn’t know what or how to test it.
Does this make sense to you?

**Comment by helencarey** [comment]
@WillHaack This may be a separate issue, but the byunlab.com interface doesn't always show them either. 

<img width="694" alt="Screen Shot 2019-08-19 at 10 18 15 PM" src="https://user-images.githubusercontent.com/8650944/63314753-b5c6b800-c2d6-11e9-965d-c5f0cb536151.png">

**Comment by WillHaack** [comment]
I'm looking into it now. My guess is the issue is with old accounts created before the firebase change. It appears to work for new accounts.
