### ISSUE TITLE
Wave freezes on free play after tutorial 

### ISSUE THREAD

**Issue by erinmdoty** [ByunLab/staRt-ionic#340]
Note: See my comment at the end of this entry - this might actually be intended behavior for the wave to freeze, but if so I think it's a little confusing for the user.

Steps: 1) create new participant 2) select "yes" for formal research pilot and enter code "biofeedback", 3) select "ok" when "introduction" box pops up, 4) select purple "start session" button, 5) select "ok" when welcome box pops up, 6)go to long word quiz and complete , 7) select "okay" when prompted to upload, 8) select "ok" when "upload complete" box pops up, 9) select "ok" when syllable quiz box pops up, 10) select syllable quiz, 11) select "ok" when syllable quiz box pops up, 11) do all words in syllable quiz, 12) select "ok" when upload box pops up, 13) select "okay" when upload complete box pops up, 14) select "ok" when prompted to navigate to tutorial, 15) navigate to tutorial, and navigate through tutorial to the end 16) at end of tutorial, select "ok" when free play box pops up (note, the box says "please navigate to free play and try out the wave for approximately five minutes" but I'm already automatically in free play at this point, so that direction is a little confusing), 16) after about 1 minute I touched the screen and the wave froze. Can't remember if I touched the screen or not when the wave froze the last few times I tried this. Able to unfreeze the wave when navigating away from free play and then back again.

**Comment by erinmdoty** [comment]
Running version 2.0.4 of staRt on iPad 4th generation (AI1458) with iOS 10.3.3

**Comment by erinmdoty** [comment]
Note: the wave froze again when I touched the screen while using free play at the beginning of a session (rather than just when using it at the end of the tutorial).

**Comment by starakaj** [comment]
Erin,

Yup, touching that do to freeze-unfreeze the wave is intended behavior. The interaction is probably a little confusing and could use some polish.

**Comment by starakaj** [comment]
Now #341 https://github.com/ByunLab/staRt-ionic/issues/341
