### ISSUE TITLE
Wave pausing needs some feedback

### ISSUE THREAD

**Issue by starakaj** [ByunLab/staRt-ionic#341]
Pausing the wave is great, but it would be helpful to have some kind of feedback to let the user know that the pausing is intentional and reversible. Something like "wave paused" or "unpause" over the pause button? Or the pause button could change to a play button after the user pauses?

**Comment by helencarey** [comment]
@erinmdoty 
It sounds like this may be related to the graphics bug in 2.0.4.
The pause/play btn should have pause/play icons that indicate the state of the wave — however the icons probably didn’t load in 2.0.4 b/c I used an incorrect library.

In 2.0.5 the pause/play interface should look like this:
<img width="1025" alt="Screen Shot 2019-04-15 at 2 06 18 PM" src="https://user-images.githubusercontent.com/8650944/56155766-af6faa80-5f89-11e9-86d9-863fdf89392d.png">

Will this address the issue?
(The design is still kind of strange. If you have any ideas on how to make it better, just let me know.)
