### ISSUE TITLE
Troubleshoot graphics conditions for TRAD vs BF in 'beachScene' logic

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#346]
v.2.0.5
_TM: in the no-biofeedback mode, for some reason the posts on the beach are not displaying, and you just see a lonely little crab with only one arm :cry:
Happens in both Quest and Free Play_

I suspect that there is some logic from the auto-service module that sets BF or TRAD, and that needs to be captured at page load in Quest and Free Play.

**Comment by helencarey** [comment]
- [ ] Fix FreePlay controller and template to switch b/t BF & NoBF based on $rootscope vars.
- [ ] Figure out how to control the Quest controller and template to do something similar via $rootscope > practice directive > words controller ???

**Comment by helencarey** [comment]
@Tjc10  @tarabyun 

ok, I believe this is correct. Pls let me know if I have missed something.
(This ticket addresses user-flow thru the study protocol and instances where the display differs based on BF or NoBF status.  In #338, I'm going to add some content, explanatory text, to the on-protocol Free Play screens. If you can think of anything else to add, lmk.)

**Sequence:**
When a user is on-protocol, they get the usual introductory prompts and then the 'navigate to Free Play' prompt. After that, their screens will differ in 3 contexts, based on whether they are doing a BF or NoBF session. The **v2.0.10** screens should look like:

**BF - Free Play** (on-protocol)
![Simulator Screen Shot - iPad Air 2 - 2019-06-26 at 17 30 00](https://user-images.githubusercontent.com/8650944/60217023-b17fa080-9839-11e9-8c76-75956922a63d.png)

**BF - Quest Config Screen** (on-protocol)
![Simulator Screen Shot - iPad Air 2 - 2019-06-26 at 17 30 16](https://user-images.githubusercontent.com/8650944/60217032-b6445480-9839-11e9-9457-05d95517b374.png)

**BF - Quest** (on-protocol)
![Simulator Screen Shot - iPad Air 2 - 2019-06-26 at 17 30 31](https://user-images.githubusercontent.com/8650944/60217043-ba707200-9839-11e9-9c26-95f4e7b86100.png)


**NoBF - Free Play** (on-protocol)
![Simulator Screen Shot - iPad Air 2 - 2019-06-26 at 16 22 34](https://user-images.githubusercontent.com/8650944/60216991-9a40b300-9839-11e9-862e-43f8b76bf32f.png)

**NoBF - Quest Config Screen** (on-protocol)
![Simulator Screen Shot - iPad Air 2 - 2019-06-26 at 16 22 59](https://user-images.githubusercontent.com/8650944/60217008-a462b180-9839-11e9-8f81-489ff02cfd9c.png)

**NoBF - Quest** (on-protocol)
![Simulator Screen Shot - iPad Air 2 - 2019-06-26 at 16 23 07](https://user-images.githubusercontent.com/8650944/60217014-a9bffc00-9839-11e9-9244-75e3d8f307f2.png)

**Comment by tarabyun** [comment]
Yes, these look good to me--thanks!

**Comment by helencarey** [comment]
**QA Checkpoints for @Tjc10 **
**changes affect:** free play and quest screens
This ticket addresses user-flow thru the study protocol, and instances where the display differs based on BF or NoBF status.

**free play & quest screens for on-protocol, biofeedback session**
- [ ] When a user is on-protocol, they get the usual introductory prompts and then the 'navigate to Free Play' prompt. Free Play should show the wave and crab scene.
- [ ] In Free Play, the sand should contain the following text: “This is the place to practice /r/; sounds on your own. There are no prompts or words to match - just try different things and see what works best.”
- User is prompted to navigate to Quest. On the Quest Config Screen (on-protocol, BF Session): 
- - [ ] should give user options to: Select /r/ Categories, Select Trial Goal, Begin Quest
- - [ ] should _not_ show the Wave Hidden toggle option
- [ ] In Quest (on-protocol, questBF), the user will see the wave and crab scene with rating btns and coin counters.

**free play & quest screens for on-protocol, non-biofeedback session**
- [ ] When a user is on-protocol, they get the usual introductory prompts and then the 'navigate to Free Play' prompt. Free Play should show the bird and kites scene.
- [ ] In Free Play, the sand should contain the following text: “This is the place to practice /r/; sounds on your own. There are no prompts or words to match - just try different things and see what works best.”
- User is prompted to navigate to Quest. On the Quest Config Screen (on-protocol, BF Session): 
-  - [ ] should give user options to: Select /r/ Categories, Select Trial Goal, Begin Quest
-  - [ ] should _not_ show the Wave Hidden toggle option
- [ ] In Quest (on-protocol, questNoBF), the users will see the bird and kites scene with rating btns and coin counters.

**free play (_not_ on-protocol)**
- [ ] Free Play should always show the wave and crab scene.
- [ ] In Free Play, the sand should contain the following text: “This is the place to practice /r/; sounds on your own. There are no prompts or words to match - just try different things and see what works best.”
	
**quest (_not_ on-protocol)**
- [ ] On the Quest Config Screen should give user options to: Select /r/ Categories, Select Trial Goal, Begin Quest _AND have a Wave Hidden toggle option_
- [ ] In Quest, the users will see the bird and kites scene if Wave Hidden toggle is selected at config.
- [ ] In Quest, the users will see the wave and crab scene if Wave Hidden toggle is not selected at config.

Let me know, if you have any questions,
-h

**Comment by tarabyun** [comment]
Thanks for these clear checkpoints, @helencarey! Just wanted to add one point of terminological clarification since @Tjc10 wasn't on our last call! "on-protocol" means signed in as a formal pilot tester; "not on-protocol" means you are using the app from a profile that is not associated with a formal pilot tester role.

**Comment by Tjc10** [comment]
Hi all, I tested the above listed scenarios in two different profiles ("TwyTest_Freeplay on-prot" and "TwyTest_Freeplay not-on-prot").  I indicated with check marks (above) all the features Helen outlined that I did in fact see.  Overall, all features appeared to work as outlined.
But please note that:
-  When I tested User is prompted to navigate to Quest. On the Quest Config Screen (both the "on-protocol, BF" session & the "on-protocol, non-BF" scenarios) should give user options to: Select /r/ Categories, Select Trial Goal, Begin Quest, ***I did get to select /r/ categories and begin quest as usual.  But the "select trial goal was set at 100 (I was not able to select a different value as my goal.  The option was locked on 100)***  This was not necessarily a problem.  Just an FYI.   
Please also note:
During "TwyTest_Freeplay on-prot" I did baseline and three sessions (2BF + 1non-BF) ---file upload errors popped up for each upload attempt.  ***No files were uploaded successfully.***
During "TwyTest_Freeplay not-on-prot" I did three sessions (2BFwave hiden toggle not selected + 1non-BF wave hidden toggle selected) ---file upload errors popped up for each upload attempt.  ***No files were uploaded successfully.***
