### ISSUE TITLE
email is carried over when you logout and create a new account.

### ISSUE THREAD

**Issue by WillHaack** [ByunLab/staRt-ionic#353]
I had an account (called Account 1) , and logged out, and then created a new account (called Account 2)with a different email.

When I made a new recording and uploaded a file while logged into Account 2, the email from Account 1 was used. So when you create a new account and login, the email is not being updated.

**Comment by WillHaack** [comment]
should be fixed with https://github.com/ByunLab/staRt-ionic/pull/368

**Comment by WillHaack** [comment]
QA Note:

- [ ] Make sure logging out ad back in clears the current participant

1. Login and pick a participant from the profile page.
2. Click Clinician's Card -> Clinician Logout
3. Login to a different account and make sure you see **Select a participant to begin** on the right, and not an already-selected account.
4. Go to Free Play and make sure there is no participant name in the top left corner.
5. Go back to Profile
6. Choose a participant
7. Go to Free Play and make sure the newly chosen participant is in the top left of the screen.

- [ ] Repeat steps 1-7 but relogin into the same account for step 3.

- [ ] Repeat steps 1-7, but instead of logging into an existing account for step 3 create a new account

**Comment by Tjc10** [comment]
Yes, all test scenarios outlined above worked as described. Encountered no issues while logging in and out of accounts.  No errors to note.  Thanks!
