### ISSUE TITLE
Smarter Carrier Phrases

### ISSUE THREAD

**Issue by WillHaack** [ByunLab/staRt-ionic#373]
Carrier phrases are currently selected randomly. At the very least they should be updated to be selected in shuffled cyclic presentation. 

To take this improvement one step further, if we have time we should rework carrier phrases. Right now they are all of some form that allows for any word to be used. " they said ___  " This is convenient for the code, but it creates bland sentences that don't have variety in the phonemes that proceed or follow the r-words. @tarabyun do SLPs usually have a stock of sentences with carrier phrases? Or is it SOP to use carrier phrases like the ones currently in the app?

**Comment by tarabyun** [comment]
Thanks for your thoughts on this. Honestly, I don't see a problem with the current carrier phrases. It's not just for code convenience that they're set up that way--it's for clinical convenience as well. I don't have a strong view on true random vs shuffled cyclic presentation of the carrier sentence frames--it's only the target words where I really care about the order of presentation.

**Comment by WillHaack** [comment]
Okay, closing this issue for now then.
