### ISSUE TITLE
Formal Session UI Improvements

### ISSUE THREAD

**Issue by WillHaack** [ByunLab/staRt-ionic#378]
- Add auto navigation for sessions
- More signposting for which step of the session you're on.

Related:
https://s18798.pcdn.co/byunlab/wp-content/uploads/sites/2008/2019/05/Master-schedule-for-staRt-app-piloting_updated2MAY2019.pdf

**Comment by WillHaack** [comment]
@tarabyun @helencarey As per my question in general chat - how should we handle auto navigation for after the 5 minutes of free play? I think there should just be a button in the bottom right corner saying "on to first quest"

**Comment by tarabyun** [comment]
I think @helencarey is the best person to weigh in on this!

**Comment by helencarey** [comment]
Anywhere is probably fine. 
In traditional ux (think webpages), the bottom right is usually the last place folks look for new info — hence f-pattern and z-pattern layouts. But for ‘games,’ none of that really matters — HUD-like info clusters around corners. 

My initial plan was to use a graphic dialog box. I haven’t built this yet, but its what I will be using throughout the practice activities for end-of-block or end-of-quest messages. 
This end-of-timer event is also marks the end of the activity, so I think a splashy interaction, like a dialog box is fine.  See img#2.

Another option would be to simply replace the timer element with a msg button. img#3

Here are some drawings.

**in game UI**
![inGame-BF](https://user-images.githubusercontent.com/8650944/64542880-5286df00-d2f2-11e9-8085-36b43581c530.png)

**img#2: end of timer dialog**
![dialogBox](https://user-images.githubusercontent.com/8650944/64543564-74349600-d2f3-11e9-95e8-e793e95640f6.png)

**img#3: end of timer button**
![button](https://user-images.githubusercontent.com/8650944/64543579-7860b380-d2f3-11e9-89fa-14ac262c9c8a.png)

**Comment by WillHaack** [comment]
The flow is done with https://github.com/ByunLab/staRt-ionic/commit/a0022aef57d5a4108019a93efd502988d19729ce, but the nice modals still need to be implemented. Assigning that task to @jonathan-chin The cards are similar to the new high score cards from @helencarey

**Comment by WillHaack** [comment]
QA Note for v3.0.2

- [ ] 

1. Create a new account named "Speedy" 
2. Make Speedy a formal tester by entering the password "biofeedback"
3. Start a formal session.
4. Make sure you are guided correctly to the quiz page. Click long word quiz and completed it.
5. Make sure you prompted to do the syllable quiz.
6. Complete the syllable quiz.
7. Make sure you are guided to the tutorial page, completed the tutorial.
8. Make sure you are guided to the free play page, stay there for a few seconds until you are told you are done.

9. Go back to profiles page and start a new session.
10. Make sure you are guided to free play, wait there for a few seconds until you are taken to the quest page.
11. Complete the quest.

Repeat steps 10-11 fifteen times (you can make it go faster by clicking quest as soon as you are navigated to free play, so you don't have to wait) 


-make sure you remember to upload this next part

12. Make sure that you are properly navigated to the quiz page for the final Long Word Quiz measure. Upload it when done.
13. Make sure you are prompted to complete the final Long Syllable Quiz. Upload it when done.

**Comment by yl5504** [comment]
Sometimes when I am in a session, there is no real-time sound wave showing in "free play" and "quest", only this static image, and those session records are named "TRAD_number" @helencarey 
![IMG_0020](https://user-images.githubusercontent.com/43120402/68902127-7b1dc180-0705-11ea-863d-deb8e5b2f816.PNG)
![IMG_0021](https://user-images.githubusercontent.com/43120402/68902128-7b1dc180-0705-11ea-827c-a511cf4e6d78.PNG)
