### ISSUE TITLE
mid-session saving feature issue, where word lists don't load properly when resuming a saved session.

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#384]
**Context:** 
User is completing an on-protocol session. They save the session. Close the app instance completely, and then relaunch it. 
When they try to resume from the saved session, often the word list won't load. 

@tjc has a good description of it in the testing notes on #273.
The way to recreate it in simulator is to stop running the build and rebuild, and then try to resume a saved-session. In other words, I was _not_ able to recreate this error in simulator by simply closing the app and relaunching it.

**Comment by jonathan-chin** [comment]
hmm, I can't seem to reproduce this error in either way. Simulator, ipad 2 12.1

if I exit the app through the hardware button and come back, I get prompted to resume and it works ok.

if I stop xcode and rebuild it, I've been able to resume without an issue.

**Comment by TJC** [comment]
> @TJC has a good description of it in the testing notes on #273.

I think you're looking for @Tjc10 rather than me?

**Comment by WillHaack** [comment]
TJC - Yes I think so, sorry about that! @jonathan-chin You're right, I can no longer reproduce this bug. I believe that this may have been fixed during the auto navigation patch - there was a bug i discovered with isRecording being set to true/false incorrectly. It may have been causing this issue. So @helencarey unless you can reproduce this issue I may close this.

**Comment by WillHaack** [comment]
Issue moved to https://github.com/ByunLab/staRt-ionic/issues/399
