### ISSUE TITLE
Same word should not appear twice in a row during quest

### ISSUE THREAD

**Issue by WillHaack** [ByunLab/staRt-ionic#389]
Right now there is a 1/word_list probability that a user will get the same word twice in a row everytime they complete a cycle. For example if they are doing a quest where the words are [roo, roh, rah] and after completing the cycle the list gets scrambled to [rah, roo, roh] they will get "rah" twice in a row.

Before I assign this, @tarabyun does this seem like an issue worth doing?

**Comment by tarabyun** [comment]
I'm pretty comfortable with true random presentation where the same word can occur more than once. I'd say we can leave it as is.
