### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by jonathan-chin** [ByunLab/staRt-ionic#394]
I came across this while trying to replicate #384 . If I'm in the middle of a quest (in the simulator) and press the home button, then try to open the app again, I crash. XCode gives the following:

```
->  0x1283a34a8: movdqa -0xc(%rdx,%rdi,4), %xmm3
EXC_BAD_ACCESS (code=1, address=0x57a950
```

this happened 3 out of 4 times when I've tried to replicate. when trying to return, the app is *completely* unresponsive.

simulating on ipad air 12.1

**Comment by WillHaack** [comment]
I am seeing this bug as well. Looking into it now.

**Comment by WillHaack** [comment]
Still looking into this, this seems to be the offending commit https://github.com/ByunLab/staRt-ionic/commit/d984819906e5bf3f33bd92139173fe4604754f61

**Comment by WillHaack** [comment]
Addressed with https://github.com/ByunLab/staRt-ionic/tree/fixHomeButtonBug .

**Comment by WillHaack** [comment]
Issue moved to https://github.com/ByunLab/staRt-ionic/issues/399
