### ISSUE TITLE
Server Monitor

### ISSUE THREAD

**Issue by WillHaack** [ByunLab/staRt-ionic#398]
Create a monitor that lets us know if our server goes down. This can be done in various ways, but it must run on a separate server than the start-server and it must be able to send a ping through slack within 1 hr of the server going down. Also, it would be nice if the monitor said "Hello, i am working" once a day in a channel, without pinging anyone.

**Comment by jonathan-chin** [comment]
target completion date: 10/31

**Comment by jonathan-chin** [comment]
ok, so we're implementing two levels of checking:

1) immediate slack pings. every hour, on the hour, the automated testing server (which, for now, is on the same server as production) will run a test upload of an audio clip. if it fails, it will immediately ping #server channel on slack.

2) backup slack pings. if the automated testing server ever goes down, healthchecks.io will also ping the #server channel. this happens with, at most, a 1 hour, 5 minute lag.

this covers a variety of error cases:

if the server code is buggy but the AWS instance is still running, we'll get an immediate slack ping.
if the entire AWS instance is down or locked up, we'll get a backup slack ping.

the code should be portable if we choose to move automated testing to a separate instance.

**Comment by jonathan-chin** [comment]
just did QA testing on all situations. works as intended.
