### ISSUE TITLE
Consolidate State Saving Code & Add Ability to Resume From Various Interrupts

### ISSUE THREAD

**Issue by WillHaack** [ByunLab/staRt-ionic#399]
We need a clear way to save state for sessions currently being recorded. Previously, this ability was reserved for formal sessions. However, everyone needs it, not just because it is useful for all users, but because we need a way to handle resuming a session when a child accidentally hits the home button. This issue thus needs to address https://github.com/ByunLab/staRt-ionic/issues/394 and https://github.com/ByunLab/staRt-ionic/issues/384 . 

The must-have goals are:

- [x] Move all state-saving logic that is not specific to formal sessions from auto-session into practice-directive. 

- [x] Add the ability to resume a session after closing the app via the home button. Ideally, the audio recording will pause and then resume when the user reopens the app. The other option, which may be easier, is to save the data from the current recording session to the files as if it were completed, and then start a new recording session (with the word list where the participant left off) when the app resumes. This is the current intended (but broken) behavior of auto sessions.

- [x] Fix resuming auto sessions.

Later time-permitting goals are to have non-protocol users to be able to save a recording session and resume in a similar way that on-protocol users can. I will try to develop with this in mind, but I am not immediately adding this feature because it raises a bunch of questions such as: What happens if an on-protocol user saves their formal-session, and then starts a regular quest, and then tries to save their regular quest?

**Comment by WillHaack** [comment]
Note:
It looks like the information related to auto-service is in inProcessSessionState and the information related to the recording session is in inProcessSession.

**Comment by WillHaack** [comment]
My projected date for finishing this is November 7th. I will try to get the first checkbox ready by tomorrow (Wednesday, October 23rd) so @helencarey is not blocked. It looks like a simple fix, but if I run into complications I may be delayed until Tuesday, October 29th.

**Comment by WillHaack** [comment]
I noticed that if you pause a session, resume it successfully, and then pause it again, you get into a strange bugged state where completing the quest does not complete the session (amongst various other glitches.)

**Comment by WillHaack** [comment]
I am not 100% sure I'll be able to finish by Wednesday November 7th. The bug that ate a lot of my time was the following:

To have code that runs when the user presses the home button, you need to add an event listener to the 'pause' event like so:

```document.addEventListener("pause", $rootScope.onPause);```

My onPause function takes the $scope.currentPracticeSession and uploads it to firebase.  (This way when a user quits out via the home button they can resume a session) The problem was that I only added the event listener once, the first time the practice directive loaded. Everything worked fine, except that the "currentPracticeSession" that was used in the onPause function was not changed for subsequent sessions. So if I were to quit out with the home button, start a new session, and then quit out with the home button again, then the session that was loaded the first time would be uploaded in place of the second session. This bug was both hard to reproduce and had to be caught in the ipad simulator.
--

Currently, I have working resuming sessions for normal users. They can resume any session at any time, including ones that get abruptly ended by the home button. What's left to be done is to test more scenarios, clean up the ui for the recording cards, clean up the code (and perhaps also the formal session resuming code), and make sure  @helencarey 's high scores calculations are reasonably handled when sessions are resumed. My projected date for completion is now Nov 12th.

**Comment by WillHaack** [comment]
QA Note (Rough Draft):

The purpose of this PR is to make it so that all users can resume where they left off in either a quiz or a quest. Your job is to go through various flows of quitting out of sessions and resuming them, with the goal of finding a flow that causes unexpected behavior/crashes the app. 

First: Create a participant RESUME-TESTER. Use this participant the entire time, and always upload the sessions. We will need to see the uploaded sessions to confirm everything is working.

OFF Protocol Testing:

- [ ] Start a syllable quest and give 2 ratings. Then end the session via the Stop Quest button in the top right. Then go to profiles->recordings and click resume on the most recent session. Make sure that the session resumes and has the same 3 ratings you gave it prior. Give 1 more rating. End the session via the top right button. Go profiles->recordings to resume the session again. Make sure that now you are at 3 ratings. Give 1 more rating, and then end the session.

- [ ] Do the same as above, but for a syllable quiz.

- [ ] Do the same first step, except this time end the session by clicking the home button on the iPad. When you resume the app, you should be taken to the profile page, and given a prompt that says you quit out of the app mid session. Click okay and then resume the session. For this step, give 3 ratings, resume, 2 ratings, resume, and then 1 rating.

- [ ] Do the same as above, but for a word quiz.

**Comment by yl5504** [comment]
[screenrecord.zip](https://github.com/ByunLab/staRt-ionic/files/3876701/screenrecord.zip)

The resume test went well, but there's something else I wanna mention. As is shown in the screen record video, I only hit the rating button once, but it skipped two words. It happened in Quest and Syllable Quiz, did not happen in Word Quiz during my testings. @helencarey

**Comment by WillHaack** [comment]
@yl5504 Interesting, good catch. Does this only happen when you resume a session?

**Comment by helencarey** [comment]
Follow-up will hopefully be address in #464.
