### ISSUE TITLE
Fix index of formal sessions to start from 1 instead of 0

### ISSUE THREAD

**Issue by WillHaack** [ByunLab/staRt-ionic#403]
For on-protocol users, the numbering of sessions uploaded to the server should start from 1 instead of 0.

Extra: Session type and number (e.g., BF_1) should be appended as part of the informative filename for uploaded audio files

**Comment by jonathan-chin** [comment]
target completion date: 11/2

**Comment by WillHaack** [comment]
@jonathan-chin I don't see a commit for this, do you have something so far / what is your new projected completion date?

@helencary tagging you too because the below goes for all three of us.

As soon as you know you can't make your proposed target date, (and at the latest 1 day before that date) post what you have so far, what issues arose, and a new goal date.

**Comment by jonathan-chin** [comment]
@WillHaack sorry about that. I just finished it.

Server downloads now append strings like BF-3 where appropriate. I did some QA testing but could use a fresh pair of eyes.

I also believe that the app starts counting sessions from 1. I pushed it to a new branch called 403 (the ticket number). Same deal: I did some QA testing but could use a fresh pair of eyes.

**Comment by jonathan-chin** [comment]
@WillHaack can we close this?

**Comment by WillHaack** [comment]
@jonathan-chin Although it's working on my end, I think we should do a QA test where someone completes the entire formal session process

**Comment by WillHaack** [comment]
QA Note:

Create a participant, Speedy, and make them a formal tester by entering in the password 'biofeedback'

- [ ] Complete the entire on-protocol flow. This means you should do two introduction quizzes, a tutorial, and then 16 sessions of quests, and then a final quiz. Please upload all the recording sessions that get completed when prompted.

**Comment by yl5504** [comment]
there's no automatic popup window to guide me to the final test

**Comment by helencarey** [comment]
Follow-up will be addressed by #462
