### ISSUE TITLE
Syllable Practice

### ISSUE THREAD

**Issue by starakaj** [ByunLab/staRt-ionic#43]
Implement syllable practice

**Comment by tarabyun** [comment]
Syllable practice should be the same as word practice, but using the attached list. (Only the first column is really necessary for your purposes.) Please repeat the presentation of the syllables (random with replacement) to match the number of items presented in word practice.

**Comment by tarabyun** [comment]
Argh, because I am a terrible person, the syllable practice list I gave you previously had errors in it. Could you incorporate the attached version instead? If the pilot goes out without this change, it's OK for this fix to happen on a longer-term schedule.
