### ISSUE TITLE
No-biofeedback

### ISSUE THREAD

**Issue by starakaj** [ByunLab/staRt-ionic#44]
Implement no-biofeedback option

**Comment by tarabyun** [comment]
Option to turn live LPC off in either Free Play, Syllable Practice, or Word Practice mode.
There should be a button in each of those modes labeled "Turn wave off." 
I don't have a strong feeling about where that button ought to go.
I also don't have a strong feeling about what visual should appear when the LPC is off.

**Comment by starakaj** [comment]
Okay, I think we're good here. Helen, want to double-check?
