### ISSUE TITLE
Do not load Free Play if no active profile is selected

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#459]
If there is no profile selected and you go to Free Play (this can happen if you log in and go to Free Play immediately), then the starfish never shows up. 

TM says: Users are reporting this as a bug, so we should require that user selects an active profile to enter Free Play. (make it a page nav condition)

**Comment by helencarey** [comment]
@jonathan-chin Could you and this to your page-loading ToDo list?

**Comment by helencarey** [comment]
@jonathan-chin It would be helpful if we also prevented navigation to Quest and Quiz if no active profile is selected. Currently, the user must go thru the config-page screens before they are told that they cannot start the Quest or Quiz session because there is no active profile selected.

**Comment by WillHaack** [comment]
https://github.com/ByunLab/staRt-ionic/commit/54bf8957376cf6889597489679f2717d96e04199
