### ISSUE TITLE
In the on-protocol prompt suite, the prompt for post-treatment assessment didn't fire.

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#462]
Per YL: There seems to be no automatic popup window to guide me to the final test.

**Comment by helencarey** [comment]
@WillHaack 

**From YL on #491** 

2. Formal Session Navigation (Fixing the problem with navigation on the last step)
Start a formal session sequence, and continue it to completion. Make sure that on the last step you are navigated to the final quiz.
I was navigated to free play, then quest, then after I complete quest, here is the pop-up screen, it did not navigate me to quiz.
![IMG_0026](https://user-images.githubusercontent.com/43120402/70661613-a88d5a80-1c32-11ea-93e4-97dd284beff2.PNG)

**Comment by WillHaack** [comment]
That is the correct behavior. I was not clear enough in my QA note. When I said final step, I was referring to the final session after completing 16 quests. When you start the final session, you should get navigated to the quiz page. You don't need to be navigated to a quiz after every quest, nor should you be.

**Comment by helencarey** [comment]
@WillHaack Would you like @yl5504 to click thru a 16 Treatment protocol to ensure the prompts are correct when navigating the the post-treatment portion? Or is that unnecessary?

protocol doc: https://starfishes.slack.com/archives/C3Y5YDVA5/p1574284237007100
