### ISSUE TITLE
Add usage data/statistics to profile

### ISSUE THREAD

**Issue by starakaj** [ByunLab/staRt-ionic#47]
Profile logs number of sessions completed in each condition, number of trials per session, percentage of trials marked correct

**Comment by gsuthers** [comment]
trails = words or syllables

**Comment by gsuthers** [comment]
@starakaj is this functionality you can add in without a proper design ? Would you be okay with putting in the functionality and then receiving a design for profiles mid fall that organizes the information/ use flow of the app?

**Comment by starakaj** [comment]
This is something that I can start implementing now. The main issue is that the profiles page is starting to get a bit cluttered, and I'd appreciate some guidance on how to un-clutter it.
