### ISSUE TITLE
Migrate to firebase

### ISSUE THREAD

**Issue by starakaj** [ByunLab/staRt-ionic#48]
Could improve our ability to flag individuals for experimental conditions

**Comment by gsuthers** [comment]
Need to confirm the costs for firebase

**Comment by starakaj** [comment]
This is basically done. Profiles can be viewed here:

https://console.firebase.google.com/u/0/project/start-app-59c52/database/firestore/data~2Fprofiles~2F78b01d29-4b73-01df-6381-0eac57dd6e50
