### ISSUE TITLE
Reevaluate how we calculate performance value for Adaptive Difficulty.

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#480]
Currently, we are calculating it twice, and not sharing the performance value. 
IMO, it should be calc'd in questScoring.js with the rest of the 'lab value' scores. (The lab values keep the research data consistent, are used for adaptive diff thresholds, etc. The display values are derived from the lab values.)
This will ensure that the scores (lab and display/user) will always change together, and 2.) performance will eventually get an end-of-block card ("Look out for new words!" #356). 

Going forward the Adaptive Diff code in the controller should only reference $scope.scores.performance and a $scope.scores.changeDifficulty (-1 || 0 || 1) and update the wordlist accordingly.

**Comment by helencarey** [comment]
### QA Checkpoints

**Changes affect:** Where in the code we calculate ‘performance’ for the adaptive difficulty feature in Quests. The calculation and thresholds remains the same, but we need to be sure all the pieces are working together in regular quests and resume-from-saved-session quests.

**Comment by yl5504** [comment]
@helencarey After I reach Difficulty Level 4 / 5, phrases / sentences appear, but they were covered by the score board.
![IMG_0028](https://user-images.githubusercontent.com/43120402/70662181-b98a9b80-1c33-11ea-9cdf-55a44e276677.PNG)

**Comment by yl5504** [comment]
@helencarey 
It is very strange - all the recordings are gone. Shows nothing under every participant's profile. 
![IMG_0031](https://user-images.githubusercontent.com/43120402/70662877-1e92c100-1c35-11ea-9cf5-2fdd65c5f81d.PNG)

**Comment by helencarey** [comment]
^ @WillHaack, I've had this happen to me a few times now also. I definitely started noticing it this week -- not sure if I saw it before. 
(remember when you said you had wrapped the profiles fetcher in a timeout fn.... could this be related?)

**Comment by helencarey** [comment]
@yl5504 Thank you for this bug catch. 
If you restart the app do the recordings come back?

**Comment by yl5504** [comment]
@helencarey Yes! Recordings come back if I restart the app, works every time

**Comment by WillHaack** [comment]
Hm yeah I've noticed this bug occasionally as well. What we need is a loading screen for the recordings. This is something we should have anyway, and with a loading display we'll be able to see if the problem is we're stuck waiting for firebase. That said I think that there is a separate problem since you can fix the issue by restarting the app.

**Comment by WillHaack** [comment]
Actually we run a request against the Start servers, not firebase, to see whether or not the recordings were uploaded.
