### ISSUE TITLE
Add Filter Order reset button to SLP Resources

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#61]
As of now, if the user changes the filter order using the slider in SLP Resources, there is no indication of what it originally was.

We want to add a button to return the filter order to the automatically calculated value.

**Comment by starakaj** [comment]
Okay, I've added the button, but I have a question: what is the automatically calculated value? How is it automatically calculated?

**Comment by tarabyun** [comment]
The value is dictated by the age/gender/height values the user entered in the profile. There should be a lookup table that converts those combinations into a default filter order for the profile. Does this ring a bell?

**Comment by starakaj** [comment]
Took a bit of searching but I found it!

https://docs.google.com/spreadsheets/d/1btsxj6m8qLuxTPiAfAaqfZhA-HefvXyEkxLtXpNehw0
