### ISSUE TITLE
Add progress bar to Probe and Practice sessions.

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#62]
It would be great to add a progress bar to the probe and practice sessions to give users feedback on their success.

**Comment by gsuthers** [comment]
@tarabyun : How does the test currently setup the list of words?

If we have a limited list size perhaps we can set a minimum number of "Decent" words/syllables completed? Then if you haven't met that target number it resurfaces prompts that you have been marked "Poor" on. So the current progress would display X/Y where Y is the total needed and X is the current number of Decent/Great prompts. If a prompt is rated Poor then X does not increase.

When implementing this we should also create a task for adding feedback at the end of one of these lists, rating how well you did (How many with each rating, which words you could work on more, etc.). Then we can praise high "Great" scores.

**Comment by tarabyun** [comment]
@gsuthers: These are great thoughts, but I see them as a bit ahead of where we are right now. The grant proposal I'm working on now includes development of features for adaptive difficulty in practice--I think this would fall under that category. **For right now, I was just thinking of a counter that shows how many trials have been completed and how many are left in a given task.**

**Comment by gsuthers** [comment]
@tarabyun sounds good. I'll put this discussion off until the next phase then. I do want to make sure we have a design well before implementation so we have time to think it through :)

**Comment by starakaj** [comment]
Ah okay, I made a new ticket for this, #92. So I'll close this one for now.
