### ISSUE TITLE
[BUG] Target slider jumping to highest value

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#65]
Seen in Word Practice. The Target slider jumps to the extreme right.
Continues to pop back up to highest value even after pressing Reset to Default

**Comment by starakaj** [comment]
Hey @gsuthers , I can't seem to reproduce this. Can you give me some steps to reproduce? For example, do you have an active profile when seeing this bug?

**Comment by gsuthers** [comment]
@starakaj , unfortunately it doesn't seem that we have much more info on this.  @tarabyun reported the bug originally, so if she has more info she can post here. Let's postpone working on it until we can reproduce it.

**Comment by tarabyun** [comment]
Sorry guys, I don't have additional information about the circumstances that produced the bug. I agree that we should postpone until someone reproduces it.
