### ISSUE TITLE
[DESIGN NEEDED] Add prompt to upload after Test Probe

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#68]
For sound upload, where does recording currently start from? Word practice only? 
For the pilot study, I would like for users to be able to queue files for upload after each of (a) syllable probe, (b) word probe, (c) syllable practice, (d) word practice.

**Comment by gsuthers** [comment]
@tarabyun Same question as the other design cards: Would you like me to postpone this until you get the beta out the door? I had it on here in case you want to get started on the Pilot Study preparation.

**Comment by tarabyun** [comment]
Oh, I misunderstood. Yes, this can be postponed until after the beta goes out. I do want it done in time for piloting.

**Comment by starakaj** [comment]
@gsuthers can you double check that this ticket is still relevant? I can upload from any and all practices and probes
