### ISSUE TITLE
[BUG] Server Upload Error clearly states issue

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#69]
After selecting 'Stop Word Practice' on Word Quest and confirming "OK" to upload the session recording, we receive an error: "index.html An error has occurred. Code = 3"

It would be preferable if the message can state "Server Upload Failed. Please check your internet connection and try again."

**Comment by gsuthers** [comment]
confirmed and passing on to Sam

**Comment by gsuthers** [comment]
@starakaj this is high priority but it can wait till after we launch the beta. IF we have time before beta launch, it'd be nice to try to fix this :)

**Comment by starakaj** [comment]
This is a server upload error. Is the device connected to a network? Either way, perhaps the error message could be more descriptive than this.

**Comment by gsuthers** [comment]
Good call. It just worked for me, so I may not have been connected to the internet at the time. I agree that better feedback would be helpful. I'll change the description and name of the ticket to match.

**Comment by gsuthers** [comment]
@tarabyun I ended the first comment with suggested text. Could you approve it or suggest a different message to display when the upload fails?

**Comment by tarabyun** [comment]
I'm fine with the longer error statement.

**Comment by gsuthers** [comment]
this is working okay. It triggered 4 times for me and I had to close four pop-ups, but that's an issue we can fix later. moving to done
