### ISSUE TITLE
[BUG] App frequently closes after a few minutes of use

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#74]
*Needs more testing with new devices*

My app consistently hid itself after 3-10 minutes of use. I'm using an iPad mini 2.

**Comment by starakaj** [comment]
Sounds like a memory issue. I'll try to track it down

**Comment by starakaj** [comment]
@gsuthers Does this require you to switch tabs a bunch? Or does the crash happen even if you just sit on one of the pages?

**Comment by gsuthers** [comment]
@starakaj good thought. It consistently happens when switching between tabs. Leaving the app open for 10+ min without changing tabs seems to have no affect.

**Comment by starakaj** [comment]
Cool, I think I've addressed this---at least I wasn't able to make it happen after several minutes of tab switching. Give it a test with the next build.

**Comment by gsuthers** [comment]
Seems good! We can keep an eye on it, but I think it may be resolved for now.

**Comment by starakaj** [comment]
Moving to done
