### ISSUE TITLE
[DESIGN NEEDED] UI redesign of "Next Word" (etc) buttons

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#75]
*requires discussion* Design for #73 

The location of the "Next Word" button was inconvenient. I think that it is makes sense for us to move buttons to the bottom and sides of the app where it is more comfortable to interact with the screen. 

Free Play uses space really well. Keeping the graph centered and adding buttons to the sides and bottom make the most sense. Buttons on top of the screen should probably only be in the corners because you can use them with your thumbs or index without covering the screen.

**Comment by gsuthers** [comment]
@tarabyun Would you like me to postpone this until you get the beta out the door? I had it on here in case you want to get started on the Pilot Study preparation.

**Comment by tarabyun** [comment]
Yes, postpone, this is a lower priority.

**Comment by gsuthers** [comment]
@tarabyun regarding buttons, this is the card for improvements to the navigation buttons. How do you feel about my notes at the top? What would you like to do about them?

**Comment by tarabyun** [comment]
Agree regarding the shape of the buttons. I also think that it would be more convenient if the buttons were placed below the LPC instead of above it.

**Comment by starakaj** [comment]
Assigning this to @awanderingorill, since css scares me

**Comment by gsuthers** [comment]
Seems the design for this is done. @awanderingorill when you told Sam that this looks feasible were you planning on implementing the design this week or doing a design for it?

If you're going to do a design, I'll leave the card here until you've finished.
If you're going to use what we've been discussing (which I'm fully in support of) then I'll swap in the new card.

[I realize this might be confusing. Lemme know if it is!]
