### ISSUE TITLE
Button UI redesign

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#76]
Buttons should be 
+ Should be aligned horizontally.
+ Should be placed in the center bottom or center middle of the screen.

**Comment by tarabyun** [comment]
Geoff, are you talking about the scoring buttons (poor/decent/great) or the navigation buttons (Next/Stop word practice)? When I made a comment about the accessibility of the buttons, I meant the location of the Next/Stop buttons; I would prefer to have them under the LPC display. The scoring buttons seem OK where they are to me.

**Comment by gsuthers** [comment]
@tarabyun These two notes are referencing improvements to the scoring buttons. I'll close this issue and make sure we have one for improving the ease of using the next/stop/etc buttons
