### ISSUE TITLE
Syllable Probe issues

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#79]
This issues are for Syllable Probe only.

+ The Probe does not always progress to next syllable -- you need to rate 3 and press 'next word' three times to move on.
+ Ends Probe automatically after 10 syllables.
+ No prompt to upload when pressing "Stop Word Practice"

**Comment by gsuthers** [comment]
@tarabyun pls let us know if you would like this to be a requirement for the beta launch.

**Comment by tarabyun** [comment]
It's OK to leave these issues unresolved in the beta launch.

**Comment by tarabyun** [comment]
Prompts related to Syllable Probe instead read Syllable Practice. e.g. "Start Syllable Practice/Stop Syllable Practice" instead of "Start Syllable Probe/Stop Syllable Probe."

**Comment by starakaj** [comment]
Should also be fixed by the fixes to #80
