### ISSUE TITLE
Word Probe issues

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#80]
There is no prompt to upload given when pressing "Stop Word Practice"

**Comment by gsuthers** [comment]
@tarabyun pls let us know if you would like this to be a requirement for the beta launch.

**Comment by tarabyun** [comment]
Nope, not required for the beta launch. Required for the pilot, though.

**Comment by tarabyun** [comment]
Prompts related to Word Probe instead read Word Practice. e.g. "Start Word Practice/Stop Word Practice" instead of "Start Word Probe/Stop Word Probe."
