### ISSUE TITLE
When swapping to a new tab with voice practice, pre-load is shown.

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#83]
When switching into Syllables or Words, all three button prompts quickly flash at the top and then disappear.

**Comment by starakaj** [comment]
Ya so I'm sad to say it but this is probably not something that we can easily fix pre-pilot. I'd punt on this until after the React Native port (which will take care of it anyway)

**Comment by gsuthers** [comment]
close this because it'll be taken care of during the React Native port
