### ISSUE TITLE
Text entry in profiles limited to 1 character

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#84]
When creating or editing a profile, can only enter 1 character per entry. This is an old bug that was closed out.

**Comment by gsuthers** [comment]
When going into profiles I immediately deleted an old one from the previous TestFlight and then noticed this bug while creating my new profile. I've restarted the app again and again and deleted and created several new profiles, so this likely isn't linked to the original profile deletion... but worth mentioning?

Entering an incorrect character throws an error: "index.html: Profile is missing some data". This is expected but gives a hint to what's happening.

Atm you can enter an approved character (letters in name or number in stats) and then follow it with a bunch of non-sense (numbers in name or letters in stats, special characters anywhere). Doing this does NOT throw the index.html error noted above. So the issue seems to be blocking the entry of text (as opposed to only being a display issue).

**Comment by starakaj** [comment]
Fixed this awhile back... had something to do with CSS. Wonder where we had the regression?

**Comment by gsuthers** [comment]
Ya I remember it was in the first build I played. Couldn't find the task :/ Surprised at the regression as well

**Comment by starakaj** [comment]
K I remember, this was caused by --webkit-user-select, and it looks like ebdaaced reintroduced the bug.

**Comment by starakaj** [comment]
K, v0.1.1 should fix this
