### ISSUE TITLE
Fonts should be consistent between tutorial images and text

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#86]
The icons for (1) (2) (3) in the tutorial images seem to use a different font than the text versions.

**Comment by starakaj** [comment]
Yup. Def a good one for @helencarey

**Comment by gsuthers** [comment]
@helencarey how's this coming along? Since it is a polish task we can move it to the next milestone, but it would be nice to demonstrate the highest level of quality possible.
