### ISSUE TITLE
Test Probe: Replace empty box with graphic

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#90]
The empty box feels like something is supposed to load but has broken. It'd be nice to have a graphic in place of the box :)

**Comment by starakaj** [comment]
Okay makes sense. How about some nice text? "Wave hidden during test probe" ? What would you like?

**Comment by tarabyun** [comment]
"This page intentionally left blank"?

I think you can just display the text "Wave hidden." Thanks!
